/*
TABLOLAR ICERISINDE ISTENILEN KAYITLARI BELIRLI KURALLARA GORE KISITLI OLARAK ALMAMIZI SAGLAYAN HAZIR SQL SORGULARI BULUNMAKTADIR.
BUNLARA GENELLIKLE AGGREGATE FOKNSIYONLARI DENMEKTEDIR.
BU FONKSIYONLAR TAMAMEN VERI KUMELEME AMACI ILE KULLANILIR.
*/

--MAX EN BUYUK VERI DEGERINI GETIRIR.
--MAKSIMUM YASA SAHIP KISILERI ADA GORE GRUPLU VE ISME GORE AZALAN OLARAK GETIREN SORGU;
SELECT Name,MAX(Age) AS Age FROM PERSON
GROUP BY Name
ORDER BY Name DESC

--MIN EN KUCUK VERI DEGERINI GETIRIR.
--MINIMUM YASA SAHIP KISILERI ADA GORE GRUPLU VE ISME GORE AZALAN OLARAK GETIREN SORGU;
SELECT Name,MIN(Age) AS Age FROM PERSON
GROUP BY Name
ORDER BY Name DESC

--AVG ORTALAMA VERI DEGERINI GETIRIR.
--ORTALAMA YASA SAHIP KISILERI ADA GORE GRUPLU VE ISME GORE AZALAN OLARAK GETIREN SORGU;
SELECT Name,AVG(Age) AS Age FROM PERSON
GROUP BY Name
ORDER BY Name DESC

--COUNT TOPLAM VERI SATIR SAYISINI GERI DONDURUR.
--TOPLAM PERSONEL SAYISINI GETIREN SORGU;
SELECT COUNT(ID) AS [CountPerson] FROM PERSON

--DEPARTMANLARA GORE PERSONEL SAYISINI GETIREN SORGU;
SELECT COUNT(ID) AS [CountPerson],Department FROM PERSON
INNER JOIN DEPARTMENT ON DEPARTMENT.DepartmentID=PERSON.DepartmentID
GROUP BY Department

--DEPARTMAN YONETICILERINE GORE PERSONEL SAYISINI GETIREN SORGU;
SELECT COUNT(ID) AS [CountPerson],DepartmentManager FROM PERSON
INNER JOIN DEPARTMENT ON DEPARTMENT.DepartmentID=PERSON.DepartmentID
GROUP BY DepartmentManager

--SUM TOPLAM VERI DEGERINI GETIRIR.
--TUM YASLARN TOPLAMINI GETIREN SORGU;
SELECT SUM(Age) AS SumAge FROM PERSON

--DEPARTMANLARA GORE TOPLAM BUTCEYI GETIREN SORGU;
SELECT SUM(PRICE.Price) AS TotalPrice, Department FROM PERSON
INNER JOIN PRICE ON PRICE.PersonId=PERSON.ID
INNER JOIN DEPARTMENT ON DEPARTMENT.DepartmentID=PERSON.DepartmentID
GROUP BY Department

SELECT * FROM PERSON

--WHERE CLAUSE VERI KUMESI UZERINDE KIYASMLAMA YAPILMASINI SAGLAR.
--TUM YASLARN TOPLAMINI BELIRLI SEHRE GORE GRUPLAYIP GETIREN SORGU;
SELECT CIty,SUM(Age) AS SumAge FROM PERSON
WHERE CIty='SARAJEVO' 
GROUP BY CIty

--HAVING; GROUP BY UZERINDEN VERI KUMESINI KIYASMLAMA YAPABILMESINI SAGLAR.
--TUM YASLARN TOPLAMINI BELIRLI SEHRE GORE GRUPLAYIP GETIREN SORGU;
SELECT CIty,SUM(Age) AS SumAge  FROM PERSON
GROUP BY CIty 
HAVING CIty='SARAJEVO'

SELECT * FROM PERSON

--ILK KOLONA GORE KAYIT SAYISINI GETIREN SORGU;
SELECT COUNT(1) SatýrSayýsý FROM PERSON

--TUM YASLARIN TOPLAMINI,ILK KOLONA GORE KAYIT SAYISINI VE YAS BAREMI OLARAK 23 TEN BUYUK OLAN KAYITLARI GETIREN SORGU;
SELECT CIty,SUM(Age) SumAge,COUNT(1) AS TotalPerson FROM PERSON
GROUP BY CIty
HAVING SUM(Age) > 23