/*
FARKLI TABLOLARDAKI VERILERI BIRLESTIREREK YENI BIR SORGU TABLOSU OLUSTURMAK ICIN TABLOLAR ARASINDA JOIN ISLEMLERI GERCEKLESTIRILIR.
MANTIGI TAMAMEN KUMELERT KURAMINDAN ESINLENILMISTIR.
*/

SELECT * FROM PERSON
SELECT * FROM DEPARTMENT

/*
INNER JOIN ILE ORTAK VERISI ESLESEN KAYITLAR GETIRILIR.
PERSON TABLOSUNDA INNER JOIN ILE ICERISINDE DEPARTMAN ID SI BULUNMAYAN KULLANICILAR GELMEZ.
*/
SELECT * FROM PERSON

SELECT * FROM PERSON P
INNER JOIN DEPARTMENT D ON P.DepartmentID=D.DepartmentID

SELECT * FROM PERSON P
INNER JOIN DEPARTMENT D ON P.DepartmentID=D.DepartmentID
WHERE P.DepartmentID IS NULL  --NULL OLAN DEGERLERI DONDUREN SORGU --NOT NULL OLAMAYN DEGERLERI GETIREN SORGU

/*
SOL TABLO BAZ ALINARAK SAG TABLODAN VERI BIRLESTIRMESI GERCEKLESTIRILIR.
PERSON TABLOSUNDA BULUNAN SIRKET BILGILERI OLMAYAN KULLANICILARIDA NULL OLMASINA RAGMEN GELIR.
*/
SELECT * FROM PERSON P
LEFT JOIN DEPARTMENT D ON P.DepartmentID=D.DepartmentID

SELECT * FROM PERSON P
LEFT JOIN DEPARTMENT D ON P.DepartmentID=D.DepartmentID
WHERE P.DepartmentID IS NULL --NULL OLAN DEGERLERI GETIREN SORGU --NOT NULL OLAMAYN DEGERLERI GETIREN SORGU

SELECT * FROM PERSON P
LEFT OUTER JOIN DEPARTMENT D ON P.DepartmentID=D.DepartmentID

SELECT * FROM PERSON P
LEFT OUTER JOIN DEPARTMENT D ON P.DepartmentID=D.DepartmentID
WHERE P.DepartmentID IS NULL --NULL OLAN DEGERLERI GETIREN SORGU --NOT NULL OLAMAYN DEGERLERI GETIREN SORGU

/*
SAG TABLO BAZ ALINARAK SOL TABLODAN VERI BIRLESTIRMESI GERCEKLESTIRILIR.
DEPARTMAN TABLOSUNDA BULUNAN KISI BILGILERI OLMAYAN KULLANICILARIDA NULL OLMASINA RAGMEN GELIR.
*/
SELECT * FROM PERSON P
RIGHT JOIN DEPARTMENT D ON P.DepartmentID=D.DepartmentID

SELECT * FROM PERSON P
RIGHT JOIN DEPARTMENT D ON P.DepartmentID=D.DepartmentID
WHERE P.DepartmentID IS NULL --NULL OLAN DEGERLERI GETIREN SORGU --NOT NULL OLAMAYN DEGERLERI GETIREN SORGU

SELECT * FROM PERSON P
RIGHT OUTER JOIN DEPARTMENT D ON P.DepartmentID=D.DepartmentID

SELECT * FROM PERSON P
RIGHT OUTER JOIN DEPARTMENT D ON P.DepartmentID=D.DepartmentID
WHERE P.DepartmentID IS NULL --NULL OLAN DEGERLERI GETIREN SORGU --NOT NULL OLAMAYN DEGERLERI GETIREN SORGU

/*
IKI TABLOYU DOGRUDAN BIRLESTIREN SORGU.
DEPARTMAN VE KULLANICI TABLOSUNDA TEKLI BAZDA FARKLI OLAN TUM VERILERI ALIR.
*/
SELECT * FROM PERSON P
FULL OUTER JOIN DEPARTMENT D ON P.DepartmentID=D.DepartmentID

SELECT * FROM PERSON P
FULL OUTER JOIN DEPARTMENT D ON P.DepartmentID=D.DepartmentID
WHERE P.DepartmentID IS NULL  --NULL OLAN DEGERLERI GETIREN SORGU --NOT NULL OLAMAYN DEGERLERI GETIREN SORGU

SELECT * FROM PERSON P
FULL OUTER JOIN DEPARTMENT D ON P.DepartmentID=D.DepartmentID
WHERE P.DepartmentID IS NOT NULL --NULL OLAN DEGERLERI GETIREN SORGU --NOT NULL OLAMAYN DEGERLERI GETIREN SORGU

SELECT * FROM PERSON P
FULL JOIN DEPARTMENT D ON P.DepartmentID=D.DepartmentID

SELECT * FROM PERSON P
FULL JOIN DEPARTMENT D ON P.DepartmentID=D.DepartmentID
WHERE P.DepartmentID IS NOT NULL --NULL OLAN DEGERLERI GETIREN SORGU --NOT NULL OLAMAYN DEGERLERI GETIREN SORGU

/*
IKI TABLOYU CAPRAZLAMA OLARAK BIRLESTIREN SORGU.
DEPARTMAN TABOSUNDAKI VERILERI KULLANICILARLA TEKRARLI OLARAK CAPRAZLAYARAK BIRLESTIRIR.
*/
SELECT * FROM PERSON 
CROSS JOIN DEPARTMENT

SELECT * FROM PERSON 
CROSS JOIN DEPARTMENT
WHERE PERSON.DepartmentID IS NULL --NULL OLAN DEGERLERI GETIREN SORGU --NOT NULL OLAMAYN DEGERLERI GETIREN SORGU

SELECT * FROM PERSON 
CROSS JOIN DEPARTMENT
WHERE PERSON.DepartmentID IS NOT NULL --NULL OLAN DEGERLERI GETIREN SORGU --NOT NULL OLAMAYN DEGERLERI GETIREN SORGU

SELECT * FROM PERSON
SELECT * FROM DEPARTMENT