/*
BAZI TABLOLAR ICERISINDE NULL DEGERLERI BULUNABILIR.
BUNLARI SORGU ILE YADA HARDCORE YONTEMLERLE DEGISTIRMEDEN FARKLI BIRKAC FONKSIYON ILE ISTEDIGINIZ ANLAMLI MODEL HALINE DONUSTUREBILIRIZ.
*/

SELECT * FROM PERSON
SELECT * FROM DEPARTMENT

--ISNULL(MEVCUT DEGER, OLMASINI ISTEDIGIMIZ/DEGISMESINI-GELMESINI DUSUNDUGUMUZ DEGER)
--DEPARTMANI BULUNMAYANLAR ICIN DEPARTMANA SAHIP DEGIL,YONETICISI BULUNMAYANLAR ICIN YONETICIYE SAHIP DEGIL DEGERLERINI DONDUREN SORGU
SELECT P.Name,P.City,P.Age,P.EMail,ISNULL(D.Department,'NOT HAVE DEPARTMENT') AS Department,
ISNULL(D.DepartmentManager,'NOT HAVE MANAGER') AS Manager 
FROM PERSON P
LEFT JOIN DEPARTMENT D ON D.DepartmentID=P.DepartmentID 

--COEALESCE ISNULL'A GORE DAHA PERFORMANSLI VE GUCLUDUR
--COALESCE(MEVCUT DEGER, OLMASINI ISTEDIGIMIZ/DEGISMESINI-GELMESINI DUSUNDUGUMUZ DEGER)
--BIRDEN COK PARAMETRE ALABILIR
--DEPARTMANI BULUNMAYANLAR ICIN DEPARTMANA SAHIP DEGIL,YONETICISI BULUNMAYANLAR ICIN YONETICIYE SAHIP DEGIL DEGERLERINI DONDUREN SORGU
SELECT P.Name,P.City,P.Age,P.EMail,COALESCE(D.Department,'NOT HAVE DEPARTMENT') AS Department,
COALESCE(D.DepartmentManager,'NOT HAVE MANAGER') AS Manager 
FROM PERSON P
LEFT JOIN DEPARTMENT D ON D.DepartmentID=P.DepartmentID 

--COALESCE(N1,N2,N3,...,NN,'ATANAN TERIM') COALESCETE ILK TERIM NULL ISE 2.TERIME,2.TERIM NULL ISE 3.TERIME,3.TERIM NULL ISE N.TERIME KADAR DEVAM EDIYOR.
--N.TERIM NULL ISE ATANMIS STRINGI VERI OLARAK YAZIYOR.
--COKLU PARAMETRE ICIN;
SELECT P.Name,P.City,COALESCE(D.Department,D.DepartmentManager,'NOT HAVE DATA') AS DepartmanDurum FROM PERSON P
LEFT JOIN DEPARTMENT D ON P.DepartmentID=D.DepartmentID

--ISNULL VE COALESCE GORE DAHA YAVASTIR
--GENELLIKLE VERILERI KENDI ICLERINDE GRUPLAMAK ICIN KULLANILIR
--DEPARTMANI BULUNMAYANLAR ICIN DEPARTMANA SAHIP DEGIL,YONETICISI BULUNMAYANLAR ICIN YONETICIYE SAHIP DEGIL DEGERLERINI DONDUREN SORGU
SELECT P.Name,P.City,P.Age,P.EMail,
CASE WHEN D.Department IS NULL THEN 'NOT HAVE DEPARTMENT'
	 ELSE D.Department
END AS Department,
CASE WHEN D.DepartmentManager IS NULL THEN 'NOT HAVE MANAGER'
	ELSE D.Department
END AS Manager 
FROM PERSON P
LEFT JOIN DEPARTMENT D ON D.DepartmentID=P.DepartmentID 