/*
TABLOLAR ÝÇERÝSÝNDE ÝSTENÝLEN KAYITLARI BELÝRLÝ KURALLARA GÖRE KISITLI OLARAK ALMAMIZI SAÐLAYAN HAZIR SQL SORGULARI BULUNMAKTADIR.
BUNLARA GENELLÝKLE AGGREGATE FOKNSÝYONLARI DENMEKTEDÝR.
*/

--MAX EN BUYUK VERI DEGERINI GETIRIR
--MAKSÝMUM YAÞA SAHÝP KÝÞÝLERÝ ADA GÖRE GRUPLU VE ÝSME GÖRE AZALAN OLARAK GETÝREN SORGU
SELECT Name,MAX(Age) AS Age FROM PERSON
GROUP BY Name
ORDER BY Name DESC

--MIN EN KUCUK VERI DEGERINI GETIRIR
--MÝNÝMUM YAÞA SAHÝP KÝÞÝLERÝ ADA GÖRE GRUPLU VE ÝSME GÖRE AZALAN OLARAK GETÝREN SORGU
SELECT Name,MIN(Age) AS Age FROM PERSON
GROUP BY Name
ORDER BY Name DESC

--AVG ORTALAMA VERI DEGERINI GETIRIR
--ORTALAMA YAÞA SAHÝP KÝÞÝLERÝ ADA GÖRE GRUPLU VE ÝSME GÖRE AZALAN OLARAK GETÝREN SORGU
SELECT Name,AVG(Age) AS Age FROM PERSON
GROUP BY Name
ORDER BY Name DESC

--SUM TOPLAM VERI DEGERINI GETIRIR
--TÜM YAÞLARN TOPLAMINI GETÝREN SORGU
SELECT SUM(Age) AS SumAge FROM PERSON

SELECT * FROM PERSON

--WHERE CLAUSE
--TÜM YAÞLARN TOPLAMINI BELÝRLÝ ÞEHRE GÖRE GRUPLAYIP GETÝREN SORGU
SELECT City,SUM(Age) AS SumAge FROM PERSON
WHERE City='SARAJEVO' 
GROUP BY City

--HAVING 
--TÜM YAÞLARN TOPLAMINI BELÝRLÝ ÞEHRE GÖRE GRUPLAYIP GETÝREN SORGU
SELECT City,SUM(Age) AS SumAge  FROM PERSON
GROUP BY City 
HAVING City='SARAJEVO'

SELECT * FROM PERSON

--ÝLK KOLONA GÖRE KAYIT SAYISINI GETÝREN SORGU
SELECT COUNT(1) SatýrSayýsý FROM PERSON

--TÜM YAÞLARIN TOPLAMINI,ÝLK KOLONA GÖRE KAYIT SAYISINI VE YAS BAREMÝ OLARAK 23 TEN BÜYÜK OLAN KAYITLARI GETÝREN SORGU
SELECT City,SUM(Age) SumAge,COUNT(1) AS TotalPerson FROM PERSON
GROUP BY City
HAVING SUM(Age) > 23









