/*
VERITABANI UZERINDE GECICI BIR SURE ICIN EK TABLOLARA IHTIYAC DUYULDUGUNDA T-SQL ILE GECICI TABLOLAR OLUSTURULUP, KULLANILIR. 
GECICI TABLOLAR, GERCEK TABLOLAR UZERINDE ISLEMLER YAPMAK YERINE, FARKLI SORGULAMALARIN YAPILABILECEGI BIR DENEME TAHTASI GIBI KULLANILIR. 
YANI ONEMLI TABLOLAR UZERINDE KRITIK SORGULAR CALISTIRMAK ZORUNDA KALINDIGINDA VE SONUCLAR TAHMIN EDILEMEYECEK GIBIYSE, GECICI BIR TABLO OLUSTURULUR VE KODLAR BU GECICI TABLO UZERINDE TEST EDILIR; DAHA SONRA ISTENILEN KODLAR GERCEK TABLOYA UYGULANIR.

TEMP TABLE YAPILARI SORGU EKRANI KAPATILDIGINDA (TEMP SORGUSU YAPILAN EKRAN/SAYFA) OTOMATIK OLARAK TABLO SISTEMDEN SILINIR.
*/

--ONCELIKLE NORMAL TABLO OLUSTURALIM
CREATE TABLE PERSONDEPARTMENT (ID INT, NAME NVARCHAR(50))

--TEMP TABLE OLUSTURALIM
CREATE TABLE #PERSONDEPARTMENT (ID INT, NAME NVARCHAR(50))

--TEMP TABLE ICERISINE DEGERLER EKLEYELIM
INSERT INTO #PERSONDEPARTMENT VALUES (1,'MIRAC')
INSERT INTO #PERSONDEPARTMENT VALUES (2,'KADIR')
INSERT INTO #PERSONDEPARTMENT VALUES (3,'OMER')
INSERT INTO #PERSONDEPARTMENT VALUES (4,'RECEP')
INSERT INTO #PERSONDEPARTMENT VALUES (5,'MUSTAFA')
INSERT INTO #PERSONDEPARTMENT VALUES (6,'EMRE')

--OLUSTURDUGUMUZ TEMP TABLE OBJEMIZI SORGULAYALIIM
SELECT * FROM #PERSONDEPARTMENT

SELECT * FROM tempdb..sysobjects
WHERE name LIKE '%#PERSONDEPARTMENT%'

--TEMP TABLE YAPISINI STORED PROCEDURE ICERISINDE KULLANIRSAK;
CREATE PROCEDURE sp_PersonDepartment
AS
BEGIN
	CREATE TABLE #PERSONDEPARTMENTTABLE (ID INT, NAME NVARCHAR(50),CITY NVARCHAR(50))
		INSERT INTO #PERSONDEPARTMENTTABLE VALUES (1,'MIRAC','ISTANBUL')
		INSERT INTO #PERSONDEPARTMENTTABLE VALUES (2,'KADIR','ANTALYA')
		INSERT INTO #PERSONDEPARTMENTTABLE VALUES (3,'OMER','BALIKESIR')
	SELECT * FROM #PERSONDEPARTMENTTABLE
END

--## KULLANILARAK BASLAYAN TEMP TABLE YAPILARI GLOBAL BAZDA OLUSUR (GLOBAL KULLANIMA ACIK OLUSUR)
CREATE TABLE ##PERSONDEPARTMENT (ID INT, NAME NVARCHAR(50))

--NOT : NORMAL TABLOLARDA OLDUGU GIBI GECICI TABLOLARDA DA INDEKS (INDEX) OLUSTURABILIR VE KIMLIK (IDENTITY) ALAN TANIMLANABILIR.
