/*
BAZI DURUMLARDA SQL VERILERINI GRUPLANMIS OLARAK INCELEMEMIZ GEREKEBILIR.

SQL SERVER ICERINSDE BULUNAN GROUP BY FONKSIYONLARI DOGRUDAN TUM IHTIYACLARIMIZI KARSILAYABILIR.
*/

USE BussinesLife
SELECT * FROM PERSON
SELECT * FROM DEPARTMENT

--BELIRLI BAZDA VERILERI GRUPLAMAK ISTERSEK
SELECT COUNT(1) AS [PERSONEL SAYISI],D.Department AS [DEPARTMAN] FROM PERSON P
INNER JOIN DEPARTMENT D ON D.DepartmentID=P.DepartmentID
GROUP BY D.Department --D.Department VS... BAZ ALINAN VERI BAREMINI BELIRLEYEBILIRIZ

--GROUP BY CUBE FONKSIYONU ILE GRUPLADIGIMIZ VERILERIN GRUPLAYIP EKSTRADAN TOPLAMINI SONUC OLARAK LISTELIYEBILIYORUZ 
SELECT COUNT(1) AS [PERSONEL SAYISI],D.Department AS [DEPARTMAN] FROM PERSON P
INNER JOIN DEPARTMENT D ON D.DepartmentID=P.DepartmentID
GROUP BY CUBE (D.Department)

--GROUP BY ROLLUP BELIRLENEN ARA DEGERLER ICIN KULLANILIR / GENELLIKLE TARIH ICEREN PERIYOTLAR BAZ ALINARAK DAHA ETKILI KULLANILIR
SELECT COUNT(1) AS [PERSONEL SAYISI],D.Department AS [DEPARTMAN] FROM PERSON P
INNER JOIN DEPARTMENT D ON D.DepartmentID=P.DepartmentID
GROUP BY ROLLUP (D.Department,D.DepartmentManager)