/*
MEVCUT SISTEMLERIMIZDE BULUNAN VERILER LISTELENIRKEN SIRALAMASI ADINA BAZI YONTEMLER BAZ ALINIR.(ORDER BY...)

BELIRLI BIR KOLON UZERINDEN SIRALAMA VE ISARETLEME YAPIP VERILERIMIZI SISTEMATIK OLARAK CEKMEK ISTERSEK TEKRARDAN BU TALEBIMIZI KARSILAYACAK MEVCUT SQL FONKSIYONLARINA BASVURABILIRIZ.
*/

USE BussinesLife

SELECT * FROM PERSON 

--DEPARTMANLARIN OLCEKLERINE GORE GRUPLAYIP ISME GORE SIRALAMAYI DENEYELIM
SELECT P.Name,P.EMail,P.City,P.BirthDate,D.DepartmentSize,
ROW_NUMBER() OVER (PARTITION BY D.DepartmentSize ORDER BY Name DESC) AS RowNumber		
FROM PERSON P
INNER JOIN DEPARTMENT D ON P.DepartmentID=D.DepartmentID

--MEVCUT SIRALAMANIN AKABINDE SIRALI SORGUMUZDA ROW NUMBER TOP 1 OLAN KAYITLARI GETIRELIM
SELECT * FROM
(
	SELECT P.Name,P.EMail,P.City,P.BirthDate,D.DepartmentSize,
	ROW_NUMBER() OVER (PARTITION BY D.DepartmentSize ORDER BY Name DESC) AS RowNumber		
	FROM PERSON P
	INNER JOIN DEPARTMENT D ON P.DepartmentID=D.DepartmentID
) K
WHERE RowNumber=1

--RANK() , ROW_NUMBER() ORANLA AYNI DEGERE SAHIP OLANLARI AYNI DEGERDE GRUPLAR
--EFEKTIF OLARAK KULLANIMI BELIRLI GRUP KIYASLARINDA (SATIS PERSONELLERI VB...) ORTAYA CIKMAKTADIR.
SELECT *,
	RANK () OVER (PARTITION BY City ORDER BY Name DESC) MyListingType	
FROM PERSON