/*
VERI TABANIMIZDA BULUNAN VERILERDE BAZEN BELIRLI BAREM ARALIGINDAKI DEGERLERI OZELLIKLERI ILE GRUPLAMAMIZ GEREKEN DURUMLAR OLABILIR.

BAZ ALINAN DEGER YOGUNLUKLU OLARAK SAYISAL OLMAKTADIR.

MEVCUT OLARAK KURGULADIGIMIZ SENARYODA TEKRARDAN SQL SERVER HAZIR FONKSIYONLARINI KULLANABILIRIZ.
*/

USE BussinesLife

/*
	NTILE(K)

	NTILE(K) FONKSIYONU CALISMA MANTIGI OLARAK VERILEN DEGERI BAZ ALARAK KAYIT SAYIMIZI BU DEGERE BOLUYOR CIKAN SONUCU UST KISMA YUVARLAYARAK 1.GRUBU OLUSTURUYOR.
	
	YUVARLANAN DEGERI MEVCUT PERSONEL SAYISINDAN CIKARIYOR KALAN PERSONEL SAYISINI K-1 ILE BOLUYOR.
	
	TEKRAR CIKAN SONUCU BIR USTE YUVARLAYARAK 2.GRUPTAKI ELEMAN SAYISINI BULUYOR.
	
	ARDISIK OLARAK BU ISLEMLER DEVEAM EDIYOR, TA KI K.GRUP OLUSTRULANA KADAR. 
*/ 

--MEVCUT PERSONELLERIMIZI MAAS BAREMLERINE GOR GRUPLAYALIM
SELECT 
	Name,EMail,City,Age,Price, 
	NTILE(5) OVER(ORDER BY PRICE.Price DESC) AS PriceGroup
	FROM PERSON
INNER JOIN PRICE ON PERSON.ID=PRICE.PersonId

/*
	SQL SERVER ICERISINDE BULUNAN NTILE() FONKSIYONU BASIT AMA BIR O KADAR DA COK ETKILIDIR.

	GRUPLANMASI GEREKEN FINANSAL,MALI,ISTATIKSEL VE SAYISAL DEGER ICEREN VERI GRUPLARI UZERINDE 
			OLDUKCA ETKILI SONUCLAR CIKARMAK ICIN BIRE BIR GUCLU BIR SQL SERVER YARDIMCI FONKSIYONUDUR. 
*/