/*
MEVCUT VERI KUMELERIMIZDE DEPARTMANLARIMIZA AIT VERILERDE BASLANGIC VE BITIS DEGERLERINI DONDURMEK ISTEYEBILIRIZ.

BU IS ICIN MIN() VE MAX() FONKSIYONLARI ILE DOGRUDAN SONUCA ULASACAGIMIZ GIBI FIRST_VALUE() VE LAST_VALUE() DEGERLERI YARDIMIYLA DA  MEVCUT ISLEMIMIZI GERCEKLESTIREBILIRZ.
*/

USE BussinesLife

/*
	MEVCUT VERITABANIMIZDA MAAS BAREMLERI SUAN AYNI;
		FAKAT BELIRLI DONEMI ASMIS PERSONELIMIZIN MAAS SKALASI DEGISTIGINDE DEGISIMI BULMAK ICIN FIRST_VALLUE() VE LAST_VALUE() FONKSIYONLARINI KULLANABILIRZ.
*/

SELECT 
	PERSON.ID,Name,EMail,City,Age,Price,Department,DepartmentManager,
	FIRST_VALUE(PRICE.Price) OVER (PARTITION BY PERSON.ID ORDER BY Name DESC) AS FirstPrice,
	LAST_VALUE(PRICE.Price) OVER (PARTITION BY PERSON.ID ORDER BY Name ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING) AS LastPrice
FROM PERSON
INNER JOIN PRICE ON PERSON.ID=PRICE.PersonId
INNER JOIN DEPARTMENT ON DEPARTMENT.DepartmentID=PERSON.DepartmentID