/*
MEVCUT IKI TABLO ARASINDA MANUEL KAYIT KARSILASTIRMA, KAYIT EKLME VS. GIBI ISLEMLERE MARUZ KALABILIRIZ.

BASIT YONTEMLERLE BUNLARI DOGRUDAN GERCEKLESTIREBILIRIZ.
*/

USE BussinesLife

--BIR TABLO UZERINDE OLUP DIGER TABLODA OLMAYAN KAYITLARIN ESLESENLERI GUNCELLEMEK, ESLESMEYENLERI SILMEK ICIN OLUSTURDUGUMUZ SORGU
MERGE INTO MERGE1 AS M
USING MERGE2 AS MM ON (M.ID=MM.ID) 
WHEN MATCHED THEN UPDATE SET M.EMail=MM.EMail; M.Password=MM.Password
WHEN NOT MATCHED BY TARGET THEN INSERT VALUES(MM.EMail,MM.Password)
WHEN NOT MATCHED BY SOURCE THEN DELETE
GO
 SELECT * FROM MERGE1;
 SELECT * FROM MERGE2;
GO

--BIR TABLO UZERINDE UYUSMAYAN KAYITLAR MEVCUTSA EKSIK OLAN TABLOYA KAYITLARI DOGRUDAN EKLEMEK ICIN OLUSTURDUGUMUZ SORGU
MERGE INTO MERGE1 AS M
USING MERGE2 AS MM ON (M.ID=MM.ID)
WHEN MATCHED THEN UPDATE 
SET M.EMail=MM.EMail; M.Password=MM.Password
WHEN NOT MATCHED BY TARGET THEN INSERT VALUES(MM.EMail,MM.Password)
GO
 SELECT * FROM MERGE1;
 SELECT * FROM MERGE2;
GO