/*
TRIGGERLAR 2 ANA YAPIDADIR.

1- DML   TRIGGER / DATA MANUPLATION LANGUAGE - TABLO VE VIEW SEVIYESINDE GERCEKLESIR.
		   									   INSERT*UPDATE*DELETE MEVCUT ISLEMLERI GERCEKLESTIGINDE CALISIRLAR.
											   AFTER VE INSTEAD OF OLARAK IKI TIPTE CALISIRLAR.
											   AFTER TETIKLEYICI ISLEMLERI BITTIKTEN SONRA KULLANILIR.
											   INSTEAD OF VIEW UZERINDE BIR TETIKLEME SONRASINDA AKTIFLESIR.
											   WRITETEXT VE TRUNCATE GIBI KOMUTLARLA TRIGGERLAR TETIKLENMEZ.
											   YAPISAL OLARAK DELETED VE INSERTED OLARAK IKI SANAL TABLO OLUSTURURLAR.
											   UPDATED OZEL OLARAK ONCELIKLE VERIYI DELETE EDIP SONRASINDA KAYDI INSERT EDER.

2- DDL   TRIGGER / DATA DEFINATION LANGUAGE -  VERI TABANI VE SERVER SEVIYESINDE GERCEKLESIR.
											   VERITABANIMI UZERINDEKI FAALIYETLERDEN TETIKLENIR.(TABLO OLUSTURMA VS.)
											   EVENTDATA() FONKSIYONU YARDIMI ILE ANLIK HAREKET DOKUMLERIMIZI TUTABILIRIZ.

BASIT TRIGGER YAPISI

		CREATE tr_NAME
		ON <TABLE>
		ON INSERT 
		AS
		BEGIN
	
			CODES
		END
*/

USE BussinesLife

--BAZEN TABLO UZERINDE YAPILAN DEGISIKLIKLERI LOG KAYDI UZERINDEN TABLO ICERISINDE TUTMAMIZ GEREKBILIR.
--MEVCUT BIR TABLO UZERINDE INSERT ISLEMI YAPILINCA LOG KAYDI ALMAK ICIN;
CREATE TRIGGER tr_tblPerson_Inserted
ON PERSON
FOR INSERT
AS
BEGIN
	DECLARE @ID INT
	SELECT  @ID=ID FROM INSERTED

	INSERT INTO CONTENT
	VALUES('YENI EKLENEN PERSONEL ID =' + CAST(@ID AS NVARCHAR(10)))
END

INSERT INTO PERSON VALUES ('SELÇUK','sel@gmail.com',1,14,'PRAG',1,1,1,'2000-01-01')

--MEVCUT OLUSTURDUGUMUZ TRIGGER DUZENLENMEK ICIN; / CREATE~ALTER 
ALTER TRIGGER tr_tblPerson_Inserted
ON PERSON
FOR INSERT
AS
BEGIN
	DECLARE @ID INT
	SELECT  @ID=ID FROM INSERTED

	INSERT INTO CONTENT
	VALUES('YENI EKLENEN PERSONEL ID =' + CAST(@ID AS NVARCHAR(10)) +' / '+ 'EKLENME TARIHI :' + CAST((SELECT GETDATE()) AS NVARCHAR(25)))
END

--MEVCUT BIR TABLO UZERINDE DELETE ISLEMI YAPILINCA LOG KAYDI ALMAK ICIN;
ALTER TRIGGER tr_tblPerson_Deleted
ON PERSON
FOR DELETE 
AS
BEGIN
	DECLARE @ID INT
	SELECT  @ID=ID FROM DELETED

	INSERT INTO CONTENT
	VALUES('SILINEN PERSONEL ID =' + CAST(@ID AS NVARCHAR(10)) +' / '+ 'SILINME TARIHI :' + CAST((SELECT GETDATE()) AS NVARCHAR(25)))
END

--MEVCUT BIR TABLO UZERINDE KAYIT DUZENLEME ISLEMI YAPILINCA LOG KAYDI ALMAK ICIN;
--**GUNCELLEMEDE SILINMIS OLAN KAYIT VE EKLENMIS OLAN KAYIT OLARAK SUREC ILERLER.
ALTER TRIGGER tr_tblPerson_Updated
ON PERSON
FOR UPDATE
AS
BEGIN
	DECLARE @ID INT
	SELECT  @ID=ID FROM DELETED

	SELECT * FROM DELETED
	SELECT * FROM INSERTED

	IF (COLUMNS_UPDATED() > 0)
		BEGIN
			INSERT INTO CONTENT
			VALUES('SILINEN PERSONEL ID =' + CAST(@ID AS NVARCHAR(10)) +' / '+ 'SILINME TARIHI :' + CAST((SELECT GETDATE()) AS NVARCHAR(25)))
	END
	ELSE
		BEGIN 
			INSERT INTO CONTENT
			VALUES('HATALI ISLEM GERCEKLESTI.')
	END 
END

UPDATE PERSON SET Name = 'YILDIRIM',EMail='yild@gmail.com',GenderID=1,Age=30,City='SPARTAK MOSKOVA',CompanyID=1,DepartmentID=1,ManagerID=1,BirthDate='1978-01-01'
WHERE ID=14

--SISTEMIMIZDE OZEL OLARAK DETAYLI BIR SEKILDE DEGISIMI YAPILAN TABLOLAR BULUNABILIR.
--ESKI GUNCELLEMELER UZERINDE YAPILAN DEGISIKLIKLER BIZIM SISTEMIMIZ ICIN ONEMLI OLABILIR.
--DEGISTIRILEN KOLONLARI KONTROL ETMEK ICIN BASITCE KONTROL TRIGGER YAPISI OLUSTURULABILIR.
--ONCESINDE BU DEGISIM VERILERINI TUTACAK BIR TABLO OLUSTURMAMIZ GEREKEBILIR.(CONTENT)
--SONRASINDA ISTEDIGIMIZ TABLO UZERINDE YAPILAN DEGISIKLIKLERI BU TABLOMUZDA TUTMAK ICIN;
CREATE TRIGGER tr_tblPerson_ForUpdate ON PERSON
FOR UPDATE
AS
BEGIN
DECLARE @ID INT
DECLARE @OLDNAME NVARCHAR(50)
DECLARE @NEWNAME NVARCHAR(50)
DECLARE @OLDEMAIL NVARCHAR(50)
DECLARE @NEWEMAIL NVARCHAR(50)
DECLARE @OLDGENDERID INT
DECLARE @NEWGENDERID INT
DECLARE @OLDAGE INT
DECLARE @NEWAGE INT
DECLARE @OLDCITY NVARCHAR(50)
DECLARE @NEWCITY NVARCHAR(50)
DECLARE @OLDCOMPANYID INT
DECLARE @NEWCOMPANYID INT
DECLARE @OLDDEPARTMENT INT
DECLARE @NEWDEPARTMENT INT
DECLARE @OLDMANGERID INT
DECLARE @NEWMANGERID INT
DECLARE @OLDBIRTHDATE NVARCHAR(25)
DECLARE @NEWBIRTHDATE NVARCHAR(25)
DECLARE @CONTENT NVARCHAR(1500)

SELECT *
	INTO #TEMPTABLE
	FROM INSERTED

		WHILE (EXISTS (SELECT ID FROM #TEMPTABLE))
		BEGIN
			SET @CONTENT = ''

	SELECT TOP 1 @ID = ID,@NEWNAME = Name,@NEWEMAIL = Email,@NEWGENDERID = GenderId, @NEWAGE = Age, @NEWCITY = City, 
	@NEWCOMPANYID = CompanyId, @NEWDEPARTMENT = DepartmentID, @NEWMANGERID = ManagerId, @NEWBIRTHDATE = BirthDate
	FROM #TEMPTABLE

	SELECT @OLDNAME = Name, @OLDEMAIL = Email, @OLDGENDERID = GenderId, @OLDAGE = Age, @OLDCITY = City,
	@OLDCOMPANYID = CompanyId, @OLDDEPARTMENT = DepartmentID, @OLDMANGERID= ManagerId, @OLDBIRTHDATE = BirthDate
	FROM DELETED WHERE ID = @ID

	SET @CONTENT = 'PERSONEL ID = ' +CAST(@ID AS NVARCHAR(10)) + 'DEGISTIRILDI.'

	IF (@OLDNAME <> @NEWNAME)
		SET @CONTENT = @CONTENT +'ISIM : '+ @OLDNAME +' DEN' + @NEWNAME + 'E DEGISTIRILDI.'
	
	IF (@OLDEMAIL <> @NEWEMAIL)	
		SET @CONTENT = @CONTENT +'EMAIL : '+ @OLDEMAIL + ' DEN' + @NEWEMAIL + 'E DEGISTIRILDI.'
	
	IF (@OLDCITY <> @NEWCITY)
		SET @CONTENT = @CONTENT +'SEHIR : '+ @OLDCITY + ' DEN' + @NEWCITY + 'E DEGISTIRILDI.'
		
	IF (@OLDBIRTHDATE <> @NEWBIRTHDATE )
		SET @CONTENT = @CONTENT +'DOGUM TARIHI'+ @OLDBIRTHDATE + ' DEN' + @NEWBIRTHDATE + ' E DEGISTIRILDI.'

		INSERT INTO CONTENT VALUES (@CONTENT)

		DELETE FROM #TEMPTABLE WHERE ID = @ID
	END
END

--VERITABANI DUZEYINDE; VERITABANIMIZDAKI DEGISIKLIKLERI LOG OLARAK TUTMAK ISTERSEK TRIGGERLAR UZERINDEN EVENTDATA() FONKSIYONU YARDIMI ILE BUNU SAGLAYABAILIRIZ.
--SERVER LOG TABLOMUZ ICIN;
USE BussinesLife
GO
CREATE TABLE [dbo].[DATABASEEVENTLOG](
	[ID] INT IDENTITY(1,1) NOT NULL,
	[EventTime] DATETIME NULL,
	[EventType] VARCHAR(15) NULL,
	[ServerName] VARCHAR(50) NULL,
	[DatabaseName] VARCHAR(50) NULL,
	[ObjectType] VARCHAR(50) NULL,
	[ObjectName] VARCHAR(50) NULL,
	[UserName] VARCHAR(50) NULL,
	[CommandText] VARCHAR (MAX) NULL
)

--SERVER LOG TRIGGERIMIZ ICIN;
CREATE TRIGGER tbl_DatabaseDDLControl
ON DATABASE 
	FOR CREATE_TABLE
AS
SET NOCOUNT ON

DECLARE @xmlEventData XML
SET @xmlEventData = EVENTDATA()

INSERT INTO [dbo].[DATABASEEVENTLOG]
(EventTime,EventType,ServerName,DatabaseName,ObjectType,ObjectName,UserName,CommandText)

SELECT 
	    REPLACE(CONVERT( VARCHAR(50), @xmlEventData.query('data(/EVENT_INSTANCE/PostTime)')),'T',' '),
				CONVERT( VARCHAR(50), @xmlEventData.query('data(/EVENT_INSTANCE/EventType)')),
				CONVERT( VARCHAR(50), @xmlEventData.query('data(/EVENT_INSTANCE/ServerName)')),
				CONVERT( VARCHAR(50), @xmlEventData.query('data(/EVENT_INSTANCE/DatbaseName)')),
				CONVERT( VARCHAR(50), @xmlEventData.query('data(/EVENT_INSTANCE/ObjectType)')),
				CONVERT( VARCHAR(50), @xmlEventData.query('data(/EVENT_INSTANCE/ObjectName)')),
				CONVERT( VARCHAR(50), @xmlEventData.query('data(/EVENT_INSTANCE/UserName)')),
				CONVERT( VARCHAR(MAX),@xmlEventData.query('data(/EVENT_INSTANCE/TSQLCommand/CommandText)'))

GO

CREATE TABLE DDLDATABASELOGTEST(ID INT IDENTITY (1,1))

--SERVER DUZEYINDE TRIGGER KONTROLU ICIN BIR PERSONELIN GIRIS SENARYOSUNU BAZ ALALIM.
--PERSONELIN SADECE GECE VARDIYASINDA SUNUCUYA ERISEBILMESINI SAGLAYAN BIR TRIGGER OLUSTURALIM.
--ONCELIKLE KULLANICIYI OLUSTURALIM.
CREATE LOGIN NightWorkPerson WITH PASSWORD = 'DarkKnight2008' 

--LOGIN KONTROLUNU SAGLAYAN TIRGGEER;
CREATE TRIGGER tr_LoginControl
ON ALL SERVER 
FOR LOGON
AS
BEGIN
	IF ORIGINAL_LOGIN()= 'NightWorkPerson' AND 
					DATEPART(HH,GETDATE()) BETWEEN 8 AND 17
	BEGIN
	ROLLBACK
	END
END
GO

--MEVCUT TRIGGERLARI BELIRLI PERIYOTLAR ICIN INAKTIF ETMEMIZ GEREKEBILIR.
--BELIRLEDIGIMIZ TRIGGERI INAKTIF ETMEK ICIN;
DISABLE TRIGGER tr_tblPerson_Inserted ON BussinesLife.PERSON

--MEVCUT SISTEMIMIZDE IC ICE BIRCOK TRIGGER BIRBIRINI TETIKLEYEBILIR.
--MEVCUT YAPIDAKI TRIGGERLARI AKTIF/INAKTIF ETMEK ICIN;
USE master
--INAKTIF DURUMA ALMAK ICIN;
GO
EXECUTE sp_configure 'nested triggers',0
RECONFIGURE WITH OVERRIDE
--AKTIF DURUMA ALMAK ICIN;
GO
EXECUTE sp_configure 'nested triggers',1
RECONFIGURE WITH OVERRIDE
GO

--TRIGGERLARIN OZ YINELEMLI DURUMUNU DUZENLEMEK ICIN;
--AKTIF DURUMA ALMAK ICIN;
ALTER DATABASE BussinesLife SET RECURSIVE_TRIGGERS ON
--INAKTIF DURUMA ALMAK ICIN;
ALTER DATABASE BussinesLife SET RECURSIVE_TRIGGERS OFF

--MEVCUT SISTEMIMIZDEN HERHANGI BIR TRIGGERI SILMEK ISTERSEK;
DROP TRIGGER tr_tblPerson_Inserted ON DATABASE