/*
TRIGGERLAR 3 TIP YAPIDADIR.

1- DML   TRIGGER / DATA MANUPLATION - INSERT*UPDATE*DELETE
2- DDL   TRIGGER
3- LOGON TRIGGER

BASIT TRIGGER YAPISI

		CREATE tr_NAME
		ON <TABLE>
		ON INSERT 
		AS
		BEGIN
	
			CODES
		END
*/

USE BussinesLife

--KAYIT OLUSTURAN TRIGGER YAPISI
CREATE TRIGGER tr_tblPerson_Inserted
ON PERSON
FOR INSERT
AS
BEGIN
	DECLARE @ID INT
	SELECT  @ID=ID FROM INSERTED

	INSERT INTO CONTENT
	VALUES('YENI EKLENEN PERSONEL ID =' + CAST(@ID AS NVARCHAR(10)))
END

INSERT INTO PERSON VALUES ('SELÇUK','sel@gmail.com',1,14,'PRAG',1,1,1,'2000-01-01')

--TRIGGER DUZENLENMEK ISTENIRSE / ALTER KOMUTU DAHIL EDILIR
ALTER TRIGGER tr_tblPerson_Inserted
ON PERSON
FOR INSERT
AS
BEGIN
	DECLARE @ID INT
	SELECT  @ID=ID FROM INSERTED

	INSERT INTO CONTENT
	VALUES('YENI EKLENEN PERSONEL ID =' + CAST(@ID AS NVARCHAR(10)) +' / '+ 'EKLENME TARIHI :' + CAST((SELECT GETDATE()) AS NVARCHAR(25)))
END

--KAYIT SILEN TRIGGER YAPISI
ALTER TRIGGER tr_tblPerson_Deleted
ON PERSON
FOR DELETE 
AS
BEGIN
	DECLARE @ID INT
	SELECT  @ID=ID FROM DELETED

	INSERT INTO CONTENT
	VALUES('SILINEN PERSONEL ID =' + CAST(@ID AS NVARCHAR(10)) +' / '+ 'SILINME TARIHI :' + CAST((SELECT GETDATE()) AS NVARCHAR(25)))
END

--KAYIT GUNCELLEYEN TRIGGER YAPISI
--GUNCELLEMEDE SILINMIS OLAN KAYIT VE EKLENMIS OLAN KAYIT OLARAK SUREC ILERLER
ALTER TRIGGER tr_tblPerson_Updated
ON PERSON
FOR UPDATE 
AS
BEGIN
	DECLARE @ID INT
	SELECT  @ID=ID FROM DELETED

	SELECT * FROM DELETED
	SELECT * FROM INSERTED

	INSERT INTO CONTENT
	VALUES('SILINEN PERSONEL ID =' + CAST(@ID AS NVARCHAR(10)) +' / '+ 'SILINME TARIHI :' + CAST((SELECT GETDATE()) AS NVARCHAR(25)))
END

UPDATE PERSON SET Name = 'YILDIRIM',EMail='yildir@gmail.com',GenderID=1,Age=30,City='SPARTAK MOSKOVA',CompanyID=1,DepartmentID=1,ManagerID=1,BirthDate='1978-01-01'
WHERE ID=14

--DEGISTIRILEN KOLONLARI KONTROL ETMEK ICIN BASITCE KONTROL TRIGGER YAPISI OLUSTURULABILIR
CREATE TRIGGER tr_tblPerson_ForUpdate ON PERSON
FOR UPDATE
AS
BEGIN
DECLARE @ID INT
DECLARE @OLDNAME NVARCHAR(50)
DECLARE @NEWNAME NVARCHAR(50)
DECLARE @OLDEMAIL NVARCHAR(50)
DECLARE @NEWEMAIL NVARCHAR(50)
DECLARE @OLDGENDERID INT
DECLARE @NEWGENDERID INT
DECLARE @OLDAGE INT
DECLARE @NEWAGE INT
DECLARE @OLDCITY NVARCHAR(50)
DECLARE @NEWCITY NVARCHAR(50)
DECLARE @OLDCOMPANYID INT
DECLARE @NEWCOMPANYID INT
DECLARE @OLDDEPARTMENT INT
DECLARE @NEWDEPARTMENT INT
DECLARE @OLDMANGERID INT
DECLARE @NEWMANGERID INT
DECLARE @OLDBIRTHDATE NVARCHAR(25)
DECLARE @NEWBIRTHDATE NVARCHAR(25)
DECLARE @CONTENT NVARCHAR(1500)

SELECT *
	INTO #TEMPTABLE
	FROM INSERTED

		WHILE (EXISTS (SELECT ID FROM #TEMPTABLE))
		BEGIN
			SET @CONTENT = ''

	SELECT TOP 1 @ID = ID,@NEWNAME = Name,@NEWEMAIL = Email,@NEWGENDERID = GenderId, @NEWAGE = Age, @NEWCITY = City, 
	@NEWCOMPANYID = CompanyId, @NEWDEPARTMENT = DepartmentID, @NEWMANGERID = ManagerId, @NEWBIRTHDATE = BirthDate
	FROM #TEMPTABLE

	SELECT @OLDNAME = Name, @OLDEMAIL = Email, @OLDGENDERID = GenderId, @OLDAGE = Age, @OLDCITY = City,
	@OLDCOMPANYID = CompanyId, @OLDDEPARTMENT = DepartmentID, @OLDMANGERID= ManagerId, @OLDBIRTHDATE = BirthDate
	FROM DELETED WHERE ID = @ID

	SET @CONTENT = 'PERSONEL ID = ' +CAST(@ID AS NVARCHAR(10)) + 'DEGISTIRILDI.'

	IF (@OLDNAME <> @NEWNAME)
		SET @CONTENT = @CONTENT +'ISIM : '+ @OLDNAME +' DEN' + @NEWNAME + 'E DEGISTIRILDI.'
	
	IF (@OLDEMAIL <> @NEWEMAIL)	
		SET @CONTENT = @CONTENT +'EMAIL : '+ @OLDEMAIL + ' DEN' + @NEWEMAIL + 'E DEGISTIRILDI.'
	
	IF (@OLDCITY <> @NEWCITY)
		SET @CONTENT = @CONTENT +'SEHIR : '+ @OLDCITY + ' DEN' + @NEWCITY + 'E DEGISTIRILDI.'
		
	IF (@OLDBIRTHDATE <> @NEWBIRTHDATE )
		SET @CONTENT = @CONTENT +'DOGUM TARIHI'+ @OLDBIRTHDATE + ' DEN' + @NEWBIRTHDATE + ' E DEGISTIRILDI.'

		INSERT INTO CONTENT VALUES (@CONTENT)

		DELETE FROM #TEMPTABLE WHERE ID = @ID
	END
END