/*
SQL SERVER UZERINDE VERI SINIFLARKEN BAZI KOSULLAMALARA VEYA KOSULLAMA OPERATORLERINE IHTIYAC DUYABILIRIZ.

BU OPERATORLER TABLO UZERINDE HERHANGI MANUPLASYON YAPMADAN VERILERI ISTENILEN KOSULLARA GORE SINIFLAR.
*/

SELECT * FROM PERSON

--CASE OPERATORU SUTUN ICERISINDEKI BELIRLI VERILERI VEYA VERI ARALIKLARINI ISTENILEN DURUMLARA GORE SINIFLAR.(ADLANDIRIR/KUMELER)
--BELIRLI DEPARTMANLARI ISTENILEN BIRIMLER ALTINDA GRUPLAYAN SQL SORGUSU;
SELECT 
Name,EMail,City,
CASE Department WHEN 'IT' THEN 'TECHICAL'
				WHEN 'FINANCE' THEN  'FINANCIAL'
				ELSE 'OPERATIONAL'
END AS DepartmentLevel,
DepartmentManager,DepartmentSize
FROM PERSON
INNER JOIN DEPARTMENT ON DEPARTMENT.DepartmentID=PERSON.DepartmentID 

--PERSONELLERIN MAAS SKALALARI UZERINDEN DURUMLARI SINIFLAYAN SQL SORGUSU;
SELECT
Name,EMail,City,BirthDate,
CASE  WHEN PRICE.Price <= 5000  THEN 'MID. LEVEL PRICE'
								ELSE 'HIGH LEVEL PRICE'
END AS PriceLevel
FROM PERSON
INNER JOIN PRICE ON PRICE.PersonId=PERSON.ID

--IF EXIST TABLO ICERISINDE BELIRLEDIGIMIZ DURUMDA/KOSULDA KAYIT VAR OLUP OLMADIGINI SORGULAR.
--PERSONELLER ARASINDA ISMI "RIZA" OLAN KAYIT BULUNUP BULUNMADIGINI ARASTIRAN SQL SORGUSU;
IF EXISTS (SELECT * FROM PERSON WHERE Name='RIZA')
BEGIN
PRINT 'KAYIT BULUNDU.'
END

--IIF OPERATORU BIR SUTUN ICERISINDEKI VERIYE GORE ISTENILEN IKI TIPTE SONUC DONDURUR.
--DEPARTMANID DURUMUNA GORE PERSONEL DURUMLARINI KIYASLAYAN SQL SORGUSU;
SELECT 
	Name,EMail,City,BirthDate,
	IIF(PERSON.DepartmentID=NULL,'DEPARTMANI YOK','DEPARTMANI MEVCUT') AS [Department?]
FROM PERSON
LEFT OUTER JOIN DEPARTMENT ON DEPARTMENT.DepartmentID=PERSON.DepartmentID