/*
BAZI DURUMLARDA MEVCUT SIRKETIMIZDE SIRKET VARLIKLARINI TARIH BAZLI OLARAK GIRIS VE CIKIS / BORC VE ALACAK OLARAK RAPORLAMAMIZ GEREKEBILIR.

ANLIK OLARAK ISTENILEN BU RAPORDA AMAC PARA DURUMUNUN TARIH BAZLI DEGISIMINI INCELEMEKTIR.

BAZ ALINAN DURUMA GORE BU BAKIE DEGISIMINE "YURUYEN BAKIYE" DENIR. 
*/

SELECT * FROM COMPANYMONEYLIMIT

--MEVCUT SIRKET VARLIK DURUMUNU KONTROL EDELIM.
--MEVCUT VARLIK DRUMUNU GETIREN SORGU;
SELECT 
	Name,
	EMail,
	MoneyType,
	MoneyCurrencyShortName,
	Money,
	AssetsRecordDate
FROM COMPANYMONEYLIMIT 
INNER JOIN MONEYASSETSTYPE ON MONEYASSETSTYPE.MoneyTypeId=COMPANYMONEYLIMIT.MoneyAssetsType
INNER JOIN MONEYCURRENCYTYPE ON MONEYCURRENCYTYPE.MoneyCurrencyTypeId=COMPANYMONEYLIMIT.MoneyCurrencyTypeId
INNER JOIN PERSON ON PERSON.ID=COMPANYMONEYLIMIT.PersonId


--ANLIK OLARAK BAKIYE DEGISIMINI "YURUYEN BAKIYEYI" (TARIH BAZLI) OLARAK VEREN SORGU;
SELECT 
	Name [KAYITEDENADI],
	EMail [EMAIL],
	MoneyType [TUR],
	MoneyCurrencyShortName [PARABIRIMI],
	CASE WHEN MoneyTypeId=1 THEN ISNULL(Money,0) END [ALACAK],
	CASE WHEN MoneyTypeId=2 THEN ISNULL(Money,0) END [BORÇ],
	SUM(ISNULL(CASE WHEN MoneyTypeId=1 THEN Money END,0)-ISNULL(CASE WHEN MoneyTypeId=2 THEN Money END,0)) OVER (ORDER BY AssetsRecordDate) AS [BAKIYE],
	AssetsRecordDate AS [KAYITTARIHI]
FROM COMPANYMONEYLIMIT 
INNER JOIN MONEYASSETSTYPE ON MONEYASSETSTYPE.MoneyTypeId=COMPANYMONEYLIMIT.MoneyAssetsType
INNER JOIN MONEYCURRENCYTYPE ON MONEYCURRENCYTYPE.MoneyCurrencyTypeId=COMPANYMONEYLIMIT.MoneyCurrencyTypeId
INNER JOIN PERSON ON PERSON.ID=COMPANYMONEYLIMIT.PersonId