/*
YAPACAGIMIZ ISLEM BIR BUTUNUN PARCASI ISE VE BU ISLEM YAPILIRKEN BIR SEKILDE KESILDIGINDE 
										VERI BUTUNLUGU BOZULACKSA YAPILAN TUM ISLEMLERIN GERI CEKILMESI ICIN "TRANSACTION" KULLANILIR. 
*/

SELECT * FROM PERSON

--ORNEK OLARAK PERSON TABLOSUNDA BULUNAN PERSONEL ISIMLERININ TAMAMINI YANLISLIKLA "BIRSEN" OLARAK GUNCELLEYELIM;
--MEVCUT ISLEMIN SQL SORGUSU;
BEGIN TRANSACTION
UPDATE PERSON
SET Name='BÝRSEN'
SELECT * FROM PERSON
WHERE Name='SILA'

--GERCEKLESTIRDIGIMIZ HATALI ISLEMDE TRANSACTION DEYIMINI TUTMUSTUK.
--YAPILAN BU HATALI ISLEMI GERI ALMAK ICIN "ROLLBACK TRANSACTION" DEYIMINI KULLANALIM.
--GUNCELLEMEYI GERI SARAN SQL SORGUSU;
ROLLBACK TRANSACTION
SELECT * FROM PERSON

--MEVCUT YAPMIS OLDUGUMUZ GUNELLEME SISTEMIMIZ ICIN UYGUNSA BU ISLEMI ONAYLAMAMIZ GEREKMEKTEDIR.
--MEVCUT ISLEMI ONAYLAYAN SQL SORGUSU;
COMMIT TRANSACTION
SELECT * FROM PERSON

--GUNCELLEME,SILME VEYA TAMAMEN TABLOYU TRUNCATE ETMEDEN KESINLIKLE TRANSACTION DEYIMI KULLANILMALIDIR.
--WEEKDAY TABLOMUZU TRUNCATE EDIP GERI GETIRMEYE CALISALIM.
--MEVCUT ISLEM ICIN GECERLI SQL SORGUMUZ;
SELECT * FROM BussinesLife.dbo.WEEKDAY
GO
	BEGIN TRANSACTION
GO
TRUNCATE TABLE BussinesLife.dbo.WEEKDAY
GO
DROP TABLE BussinesLife.dbo.WEEKDAY
GO
SELECT * FROM WEEKDAY

--SILINEN TABLOYU GERI GETIRMEYE CALISALIM.
--MEVCUT ISLEMIN SQL SORUGUSU;
ROLLBACK TRANSACTION
GO
SELECT * FROM BussinesLife.dbo.WEEKDAY

--SERVER UZERINDE ACIK TRANSACTIONLARI KONTROL EDELIM.
--MEVCUT SQL SORGUSU;
DBCC OPENTRAN
EXECUTE sp_who 52
SELECT @@TRANCOUNT

