/*
YAPACAGIMIZ ISLEM BIR BUTUNUN PARCASI ISE VE BU ISLEM YAPILIRKEN BIR SEKILDE KESILDIGINDE 
										VERI BUTUNLUGU BOZULACKSA YAPILAN TUM ISLEMLERIN GERI CEKILMESI ICIN "TRANSACTION" KULLANILIR. 
*/

SELECT * FROM PERSON

--ORNEK OLARAK PERSON TABLOSUNDA BULUNAN PERSONEL ISIMLERININ TAMAMINI YANLISLIKLA "BIRSEN" OLARAK GUNCELLEYELIM;
--MEVCUT ISLEMIN SQL SORGUSU;
BEGIN TRANSACTION
UPDATE PERSON
SET Name='BÝRSEN'
SELECT * FROM PERSON
WHERE Name='SILA'

--GERCEKLESTIRDIGIMIZ HATALI ISLEMDE TRANSACTION DEYIMINI TUTMUSTUK.
--YAPILAN BU HATALI ISLEMI GERI ALMAK ICIN "ROLLBACK TRANSACTION" DEYIMINI KULLANALIM.
--GUNCELLEMEYI GERI SARAN SQL SORGUSU;
ROLLBACK TRANSACTION
SELECT * FROM PERSON

--MEVCUT YAPMIS OLDUGUMUZ GUNELLEME SISTEMIMIZ ICIN UYGUNSA BU ISLEMI ONAYLAMAMIZ GEREKMEKTEDIR.
--MEVCUT ISLEMI ONAYLAYAN SQL SORGUSU;
COMMIT TRANSACTION
SELECT * FROM PERSON

--GUNCELLEME,SILME VEYA TAMAMEN TABLOYU TRUNCATE ETMEDEN KESINLIKLE TRANSACTION DEYIMI KULLANILMALIDIR.
--WEEKDAY TABLOMUZU TRUNCATE EDIP GERI GETIRMEYE CALISALIM.
--MEVCUT ISLEM ICIN GECERLI SQL SORGUMUZ;
SELECT * FROM BussinesLife.dbo.WEEKDAY
GO
	BEGIN TRANSACTION
GO
TRUNCATE TABLE BussinesLife.dbo.WEEKDAY
GO
DROP TABLE BussinesLife.dbo.WEEKDAY
GO
SELECT * FROM WEEKDAY

--SILINEN TABLOYU GERI GETIRMEYE CALISALIM.
--MEVCUT ISLEMIN SQL SORUGUSU;
ROLLBACK TRANSACTION
GO
SELECT * FROM BussinesLife.dbo.WEEKDAY

--SERVER UZERINDE ACIK TRANSACTIONLARI KONTROL EDELIM.
--MEVCUT SQL SORGUSU;
DBCC OPENTRAN
EXECUTE sp_who 52
SELECT @@TRANCOUNT

--TRANSACTION UZERINDE TRY-CATCH KULLANIMI MEVCUTTUR.
--MEVCUT SQL SORGUSU;
BEGIN TRY
	DECLARE @SAYI INT = 10/0
END TRY
BEGIN CATCH
	SELECT	
		ERROR_NUMBER() AS HATA_NUMARASI,
		ERROR_SEVERITY() AS HATA_SEVIYESI,
		ERROR_STATE() AS HATA_BILDIRIMI,
		ERROR_LINE() AS HATA_SATIRI,
		ERROR_MESSAGE() AS HATA_MESAJI,
		ERROR_PROCEDURE() AS HATA_YAPAN_PROSEDUR
END CATCH

--ACIK KALMIS TRANSACTIONLARIMIZIN KONTROLUNU GERCEKLESTIREBILIRIZ.
--MEVCUT SQL SORGUSU;
DBCC INPUTBUFFER(54)

--SISTEMIMIZDE BULUNAN KULLANICILARIN TANIMLADIGI TUM TRANSACTIONLARI KONTROL EDEBILIRIZ.
--MEVCUT SQL SORGUSU;
SELECT * FROM sys.dm_tran_session_transactions

/*
VERITABANIMIZ UZERINDE ISLEM YAPILIRKEN AYNI LOCAL DEGISIKLIKLER ICIN GERCEKLESECEK EYLEMLER BIRBIRINI EZEBILIR.

BUNUN ICIN "ISOLATION LEVEL" YONTEMLERI KULLANILIR.

		1-READ COMMITTED (DEFAULT)
		2-READ UNCOMMITTED
		3-REPEATABLE READ
		4-SERIALIZABLE
		5-SNAPSHOT
*/

--VERITABANI SEVIYESINDE ISOLATION LEVEL TANIMLAMASI ICIN MEVCUT SQL SORGUSU;
ALTER DATABASE "database_name" SET "ISOLATION-LEVEL" ON

--TRANSACTION SEVIYESINDE ISOLATION LEVEL
SET TRANSACTION ISOLATION LEVEL "ISOLATION-LEVEL"

--MEVCUT BIR TABLOYU KILITLEMEDEN SORGU DONDURMEK GEREKEBILIR.
--MEVCUT SQL SORGUSU;
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SELECT * FROM PERSON

--VEYA

SELECT * FROM PERSON WITH NOLOCK