/*
VERITABANIMIZ UZERINDE BAZI KULLANICILARA KISITMALAM GETIRMEMIZ SADECE YAPACAGI ISLEMLER UZERINDEN YETERSIZ KALABILIR. (KULLANICI TIPI)

MEVCUT TABLOLARIMIZ UZERINDE GIZLENMESI GEREKEN VERILERI BULUNABILIR.
*/

--PERSON TABLOSUNDA BULUNAN BirthDate SUTUNUNU MASKELEYELIM.
--MEVCTU SQL SORGUSU;
ALTER TABLE PERSON
ALTER COLUMN BirthDate ADD MASKED WITH ( FUNCTION = 'default()')

--SADECE SELECT ATACAK BIR KULLANICI OLUSTURALIM.
--MEVCUT SQL SORGUSU;
CREATE USER OnlySelectUser WITHOUT LOGIN

--OnlySelectUser KULLANICISI PERSON TABLOSUNDA SADECE SELECT SORGUSU GERCEKLESTIREBILSIN.
--MEVCUT SQL SORGUSU;
GRANT SELECT ON PERSON TO OnlySelectUser

--OnlySelectUser KULLANICISI ILE TABLOYA GENEL SELECT ATALIM VE TARIH YAPISINI KONTROL EDELIM.
----MEVCUT SQL SORGUSU;
--CIKTI OLARAK TUM TARIHLER = 1900-01-01 00:00:00.000 OLARAK GELIR.
EXECUTE AS USER = 'OnlySelectUser'
SELECT * FROM PERSON
REVERT

--PERSON TABLOSUNDA BULUNAN EMail SUTUNUNU MASKELEYELIM.
--MEVCTU SQL SORGUSU;
ALTER TABLE PERSON
ALTER COLUMN EMail ADD MASKED WITH ( FUNCTION = 'email()')

--OnlySelectUser KULLANICISI ILE TABLOYA GENEL SELECT ATALIM VE TARIH YAPISINI KONTROL EDELIM.
--MEVCUT SQL SORGUSU;
--CIKTI OLARAK TUM EMAILLER = nXXX@XXXX.com YAPISINDA GELIR.
EXECUTE AS USER = 'OnlySelectUser'
SELECT * FROM PERSON
REVERT

--PERSON TABLOSUNDA BULUNAN Age SUTUNUNU MASKELEYELIM.
--MEVCTU SQL SORGUSU;
ALTER TABLE PERSON
ALTER COLUMN Age ADD MASKED WITH ( FUNCTION = 'random(18,120)')

--OnlySelectUser KULLANICISI ILE TABLOYA GENEL SELECT ATALIM VE TARIH YAPISINI KONTROL EDELIM.
--MEVCUT SQL SORGUSU;
--CIKTI OLARAK TUM YAS ARALIKLARI 18-120 ARALIGINDAKI HERHANGI BIR DEGERDE GELIR.
EXECUTE AS USER = 'OnlySelectUser'
SELECT * FROM PERSON
REVERT

--PERSON TABLOSUNDA BULUNAN City SUTUNUNU MASKELEYELIM.
--MEVCTU SQL SORGUSU;
ALTER TABLE PERSON
ALTER COLUMN Phone ADD MASKED WITH ( FUNCTION = 'partial(1,"XXXXXXXXXXXX",5)')

--OnlySelectUser KULLANICISI ILE TABLOYA GENEL SELECT ATALIM VE TARIH YAPISINI KONTROL EDELIM.
--MEVCUT SQL SORGUSU;
--CIKTI OLARAK TUM PHONE SUTUNU = 0XXXXXXXXXXXX42324 TIPINDE DEGER GELIR.
EXECUTE AS USER = 'OnlySelectUser'
SELECT * FROM PERSON
REVERT

--MASKELEME ISLEMINI KULLANICIDAN KALDIRMAK GEREKEBILIR.
--MEVCUT SQL SORGUSU;
GRANT UNMASK TO OnlySelectUser

--DOGRUDAN TUM MASKELEMELERI KALDIRMAMIZDA ISTENEBILIR.
--MEVCUT SQL SORGUSU;
ALTER TABLE PERSON
ALTER COLUMN BirthDate DROP MASKED
ALTER TABLE PERSON
ALTER COLUMN EMail DROP MASKED
ALTER TABLE PERSON
ALTER COLUMN Age DROP MASKED
ALTER TABLE PESRON
ALTER COLUMN Phone DROP MASKED
REVERT