/*
BAZEN VERITBANIMIZDA BIRDEN COK KISI CALISABILIR.

MEVCUT ORTAK EKIP ARKADAASLARI ILE AYNI TABLOLARI KULLANMAK ZORUNDA KALABILIRIZ.

FAKAT BU TABLOLARDA KISIYE AIT OZEL VERILER BULUNABILIR.

BUNUN ICIN SQL SERVER ICERISNDE BULUNAN YAPI ILE KURGU OLUSTURMAMIZ GEREKIR.

BUNA "ROW LEVEL SECURITY*" DENIR. *SATIR BAZLI GUVENLIK

*/

SELECT * FROM PERSON

--KULLANICIMIZA SELECT YETKISI VERELIM.
--MEVCUT SQL SORGUSU;
GRANT SELECT ON dbo.PERSON TO MÝRAÇ

EXECUTE AS USER ='MÝRAÇ'
SELECT * FROM dbo.PERSON;
REVERT
GO


/*ASAGIDAKI YAPIMIZDA MEVCUT HERHANGI BIR "KULLANICI VE CALISAN ADI" ILE ESLESTIRDIGIMIZ EKIP UYEMIZIN 
										SADECE KENDISINE AIT SQL VERILERINI GORMESINI SAGLAYAN BIR KURGU OLUSTURDUK.
*/
--MEVCUT SQL SORGUSU;
CREATE FUNCTION dbo.RowLevelSecurity (@username AS sysname)
RETURNS TABLE
WITH SCHEMABINDING
AS
RETURN SELECT 1 AS RowLevelResult
WHERE @username = USER_NAME()
GO

CREATE SECURITY POLICY RowLevelSecurity
ADD FILTER PREDICATE dbo.RowLevelSecurity(Name) ON dbo.PERSON
WITH (STATE = ON);
GO

--TEKRAR KULLANICIMIZLA KONTROL GERCEKLESTIRELIM.
--MEVCUT SQL SORGUSU;
EXECUTE AS USER='MÝRAÇ'
SELECT * FROM PERSON;
REVERT

--EK OLARAK KULLANICIMIZA "SHOW PLAN" YETKISI VERELIM.
--MEVCUT SQL SORGUSU;
GRANT SHOWPLAN TO MÝRAÇ

--TUM ROW LEVEL YAPIMIZI DROP EDEBILIRZ.
--MEVCUT SQL SORGUSU;
DROP SECURITY POLICY dbo.RowLevelSecurity
GO
DROP FUNCTION dbo.RowLevelSecurity
GO
