/*
SQL SERVER 2017'DE T-SQL FONKSIYONLARINA YENILERI EKLENMISTIR.

MEVCUT BIR KACI ASAGIDAKI GIBIDIR.
*/

USE BussinesLife

SELECT * FROM PERSON

--CONCAT_WS() FONKSIYONU CONCAT FONKSIYONU GIBI VERILERI BIRLESTIRMEMIZI SAGLAR.
--ILK PARAMETRESI AYRACI BELIRTIR.
--N TANE DEGISKEN ALABILIR.
--MEVCUT SQL SORGUSU;
SELECT CONCAT_WS('_',Name,City,Age) AS [KISA OZLUK BILGI] FROM PERSON

--STRING_AGG() FONKSIYONU BIRDEN FAZLA METIN TURUNDEKI SUTUNLARI BIRLESTIRMEK ICIN KULLANILIR.
--CIKTI TEK SATIR OLARAK VERILIR.
--MEVCUT SQL SORGUSU;
SELECT STRING_AGG(Department,',') AS [DEPARTMANLAR] FROM DEPARTMENT

--SIRKETIMIZDE CALISAN PERSONELLERI DEPARTMAN OLARAK TEK SATIRDA YAZDIRALIM.
--MEVCUT SQL SORGUSU;
SELECT Department,STRING_AGG(Name,' / ') WITHIN GROUP (ORDER BY PERSON.Name DESC) AS [DEPARTMAN CALISANLARI] FROM DEPARTMENT
LEFT OUTER JOIN PERSON ON PERSON.DepartmentID=DEPARTMENT.DepartmentID
GROUP BY Department
/*
CIKTISI;

FINANCE			SEHER / NAZLI  / MUSTAFA / KADÝR
IT				YILDIRIM / VÝLDAN / ÞAHÝN / SELÇUK / RIZA / MÝRAÇ / BARBAROS
OPERATIONS		ÞULE  / ÖMER / EMRE
SALES			ÞÖHRET / RECEP / RECEP / NERMÝN / ÝSMET
TECHNIQUE		NULL
*/

--TRNASLATE() FONKSIYONU REPLACE() FONKSIYONUNA BENZER SEKILDE SORGU ICERISINDE KULLANICIYA YARDIMCI OLUR.
--TRANSLATE() FONKSIYONUN YINELEYICI OZELLIGI SAYESINDE TANIMLANAN DEGISKEN ICERISINDE DINAMIK ARAMA YAPIP ISTENILEN KARAKTERI DUZENLEMEMIZE YARDIMCI OLUR.
--MEVCUT TANIMLADIGIMIZ STATIK BIR VERIDEKI KARAKTERLERI DUZENLEMEK ISTEDIGIMIZI FARZ EDELIM.
--MEVCUT SQL SORGUSU;
DECLARE @QUERRY AS NVARCHAR(MAX) = '{ MIRAC OZTURK [2019-09-07] TARIHLI TEST_VERISI. }'
SELECT TRANSLATE(@QUERRY,'{[]}_','(())-') AS [DUZENLENMIS VERI]
/*
CIKTISI;

( MIRAC OZTURK (2019-09-07) TARIHLI TEST-VERISI. )
*/

--TRIM() FONKSIYONU VERI ICESINDEKI BASLANGIC VE BITIS BOSLUKLARINI SILMEMIZE YARDIMCI OLUR.
--2017 ONCESINDE LTRIM() VE RTRIM() ILE TEK TEK BU ISLEMLERI GERCEKLESTIRMEMIZ GEREKIYORDU.
--ORNEK OLARAK BOSLUKLAR ICEREN BIR VERI TANIMLAYIP BU BOSLUKLARI ORTADAN KALDIRALIM.
--MEVCUT SQL SORGUSU;
DECLARE @QUERRY AS NVARCHAR(MAX) = '   MIRAC OZTURK 2019-09-07 TARIHLI TEST_VERISI.  '
SELECT TRIM(@QUERRY) AS [DUZENLENMIS VERI]