--SISTEMIMIZDE GERCEKLESTIRDIGIMIZ ANLIK OLARAK SORGUSUNUN SURESINI SORGULAYARAK ELDE EDEBILIRIZ.
--MEVCUT SQL SORGUSU;
DBCC DROPCLEANBUFFERS WITH NO_INFOMSGS

DECLARE @i INT, @d DATETIME2(7) = SYSUTCDATETIME();
DECLARE C CURSOR  LOCAL FAST_FORWARD
FOR 
	SELECT TOP (500)*
		FROM PERSON AS P
		ORDER BY P.Name DESC
OPEN C; FETCH C INTO @i;
WHILE @@FETCH_STATUS = 0
BEGIN 
	SET @i +=@i;
	FETCH C INTO @i;
END
CLOSE C; DEALLOCATE  C;
PRINT 'BU ISLEM '+RTRIM(DATEDIFF(MILLISECOND,@d,SYSUTCDATETIME())) +' MILISANIYE SURDU.'

--MEVCUT SQL SORGULARIMIZDA SUREKLI OLARAK BIR ARAMA GERCEKLESTIRIRIZ.
--BU ARAMADA HATIRLAYAMADIGIMIZ VERI KISIMLARINI "LIKE '%KELIME%' " ILE BULABILIRIZ.
--FAKAT BUNU BIRAZ DAHA DINAMIK HALE GETIREBILIRIZ.
--MEVCUT SQL SORGUSU;
DECLARE
	@Name	NVARCHAR(MAX) = N'MÝ'
SELECT 
	P.ID,P.Name,P.BirthDate,P.City
	FROM PERSON P
		WHERE P.Name LIKE '%'+@Name+'%'