/*
BAZEN TABLOLARIMIZDAKI VERILERI PASIFE CEKMEK YERINE DOGRUDAN SILMEMIZ GEREKEBILIR.
*/

--SILINEN LOG KAYITLARINI TUTACAGIMIZ TABLOMUZU OLUSTURALIM.
--OLUSTURDUGUMUZ TABLONUN ICERINI MEVCUT SQL KODU ILE INCELEYELIM;
SELECT * FROM TESTLOG

--SILECEGIMIZ TABLO VE KOSULUMUZA GORE BIR SORGU BELIRLEYELIM.
--MEVCUT TABLOMUZDA TEST ADI TEK HARF GIRILEN KAYITLARI UYARI ILE DUZENLEYELIM.
--MEVCUT SQL SORGUSU;
DELETE FROM TEST WHERE LEN(TestAdi) < 2 AND TestAdi<>'X' 

DECLARE @TestAdi NVARCHAR(MAX) = 'TEST ADI UYGUN OLARAK GIRILMEMIS'
DECLARE @TestId INT = SCOPE_IDENTITY()

SET IDENTITY_INSERT TEST OFF

DBCC CHECKIDENT (TEST,RESEED,0)

SET IDENTITY_INSERT TEST ON

INSERT INTO TESTLOG VALUES(@TestAdi,GETDATE())

--SELECT * FROM TEST