/*
BAZEN OZDES SUTUNLARA SAHIP BIR VEYA BIRDEN FAZLA SUTUNU OLAN FARKLI EN AZ IKI TABLODAN VERILERI BUIRLESTIREREK ALMAMIZ GEREKEBILIR.
COK BASIT BIR SEKILDE VERILERI TEKRARLI VEYA TEKRARSIZ OLARAK SORGULAYABILIRIZ.
*/

--TEKRAR EDEN VERILERI DAHIL ALMAK ICIN UNION ALL KULLANILIR
--TUM IKI TABLO VERISINI ALMAK ISTERSEK SUTUNLAR AYNI SAYIDA VE OZDES OLMALI
SELECT * FROM PERSON1
UNION ALL
SELECT * FROM PERSON2

--ISME GORE AZALAN OLARAK SIRALI
SELECT * FROM PERSON1
UNION ALL
SELECT * FROM PERSON2
ORDER BY Name DESC

--TEKRAR EDEN VERILER DISINDAKILERI ALMAK ICIN UNION KULLANILIR
--SORGU CALISIRKE TEKRAR EDENLERI GOZ ARDI EDER
--TUM IKI TABLO VERISINI ALMAK ISTERSEK SUTUNLAR AYNI SAYIDA VE OZDES OLMALI
SELECT * FROM PERSON1
UNION 
SELECT * FROM PERSON2

--ISME GORE AZALAN OLARAK SIRALI
SELECT * FROM PERSON1
UNION 
SELECT * FROM PERSON2
ORDER BY Name DESC