/*
BAZEN MEVCUT SORGULARIMIZDA SORGU ICERISINDE FARKLI BIR SORGU KULLANIP, 
				ANA SORGUMUZ UZERINDE OLUSTURDUGUMUZ BU ALT SORGU ICERISINDEKI VERILERE YONELIK BILGI ALMAMIZ GEREKEBILIR.

KOMPLEKS OLARAK GORULSEDE IC ICE TABLO OLUSTURUP ALT TABLO UZERINDEN ANA TABLOMUZA VERI AKTARMAMIZ BASITCE ANA MANTIGIMIZDIR.

*/

SELECT * FROM PRODUCT
SELECT * FROM PRODUCTSALES

--ANA URUNLER TABLOMUZDAN SATISLAR TABLOMUMUZA GECIP URUNLERIN SATIS MIKTARLARI VE SATIS ADETLERINI BULALIM.
--MEVCUT SQL SORGUSU;
SELECT PRODUCT.ProductName AS URUNADI
	  ,(SELECT SUM(Quantity) FROM PRODUCTSALES WHERE PRODUCTSALES.SalesProductId=PRODUCT.ProductId) AS [MIKTAR]
	  ,(SELECT SUM(Price) FROM PRODUCTSALES WHERE PRODUCTSALES.SalesProductId=PRODUCT.ProductId) AS [TOPLAMTUTAR]
FROM PRODUCT

--URUNLER TABLOSU UZERINDEN SATISLAR TABLOSUNA GECIP SATISI OLMAYAN URUNLERIMIZI BULALIM.
--MEVCUT SQL SORGUSU;
SELECT PRODUCT.ProductName AS URUNADI
FROM PRODUCT
WHERE PRODUCT.ProductId NOT IN (SELECT DISTINCT PRODUCTSALES.SalesProductId FROM PRODUCTSALES)

--SATISI OLAN URUNLERIMIZI BULALIM.
--MEVCUT SQL SORGUSU;
SELECT PRODUCT.ProductName AS URUNADI
FROM PRODUCT
WHERE PRODUCT.ProductId IN (SELECT DISTINCT PRODUCTSALES.SalesProductId FROM PRODUCTSALES)