/*
BAZEN TEST VERILERI OLUSTURMAK ICIN MEVCUT TABLOLARIMIZA RASTGELE DEGERLER EKLEMEMIZ GEREKEBILIR.

BUNU SQL MANAGEMENT STUDIO ICERISINDEKI HAZIR FONKSIYONLARLA GERCEKLESTIREBILIRIZ.
*/

--IKI DEGER ARASINDA VERI EKLEMEK ICIN RASTGELE SAYILAR OLUSTURAN BIR YAPI GEREKEBILIR.
--MEVCUT SQL SORGUSU;
DECLARE @LowNumber  INT
DECLARE @HighNumber INT

SET @LowNumber =1
SET @HighNumber=1

DECLARE @Random     INT

WHILE (1 = 1)
BEGIN
SELECT @Random = ROUND((@HighNumber-@LowNumber) * RAND(CONVERT(VARBINARY, NEWID())),0)+1
	   PRINT @Random

	   IF(@Random <1 OR @Random >5)
	   BEGIN 
			PRINT 'HATA -' + CAST(@Random AS NVARCHAR(5))
			BREAK
	   END
END


--BAZEN RASTGELE HERHANGI BIR TABLOYA BIRDEN FAZLA BELIRLI DEGERLERI EKLEMEK GEREKEBILIR.
--MEVCUT SQL SORGUSU;
DECLARE @RandomSalesProductId INT
DECLARE @RandomQuantity INT
DECLARE @RandomPrice INT
DECLARE @HighQuantity INT
DECLARE @LowQuantity  INT
DECLARE @HighPrice INT
DECLARE @LowPrice  INT
DECLARE @SalesProductId INT
DECLARE @Reapeter INT

SET @LowQuantity  =1
SET @HighQuantity =10
SET @LowPrice  =100
SET @HighPrice =10000
SET @SalesProductId = 1
SET @Reapeter = 1

WHILE (@Reapeter <= 10000)
BEGIN
		--SELECT * FROM PRODUCTSALES
		SELECT @RandomSalesProductId = ROUND (@SalesProductId  * RAND(CONVERT(VARBINARY, NEWID())),0)+1
		SELECT @RandomQuantity = ROUND ((@HighQuantity - @LowQuantity )  * RAND(CONVERT(VARBINARY, NEWID())),0)+1
		SELECT @RandomPrice = ROUND ((@HighQuantity - @LowQuantity )  * RAND(CONVERT(VARBINARY, NEWID())),0)+1

		INSERT INTO PRODUCTSALES
		VALUES (@RandomSalesProductId,@RandomQuantity,@RandomPrice)

		PRINT @Reapeter
		SET @Reapeter = @Reapeter + 1
END

--MEVCUT TABLOMUZ ICERISINDEKI TUM TEXT DEGERLERINI DEGISTIRMEMIZ GEREKEBILIR.
--MEVCUT SQL SORGUSU;
DECLARE @EskiDeger NVARCHAR(50)=''
DECLARE @YeniDeger NVARCHAR(50)=''
UPDATE PRODUCT
SET ProductName = REPLACE(ProductName,@EskiDeger,@YeniDeger)