/*
MSSQL ICERISINDE BAZI SUTUNLARI ILGILI TABLO ICERISINDEKI SUTUNLAR UZERINDEN HESAPLAYARAK ELDE EDEBILIRIZ.
*/

--BASIT BIR FATURA TABLOSU OLUSTURALIM.
--ILGILI SQL SORGUSU;
--PERSISTED EKI YAZILDIGINDA SATIRLARIN HESAPLANMASI VE KULLANILMASI SIRASINDA TEKRAR HESAPLANIR.
CREATE TABLE FATURA
(
FATURA_NO INT NOT NULL IDENTITY,
TARIH DATE NOT NULL,
MUSTERI_NO INT NOT NULL,
IRSALIYE_NO INT NOT NULL,
TOPLAM_TUTAR DECIMAL (18,4) NOT NULL,
TOPLAM_KDV DECIMAL (18,4) NOT NULL,
GENEL_TOPLAM AS TOPLAM_TUTAR+TOPLAM_KDV PERSISTED
)

SELECT * FROM FATURA

INSERT INTO FATURA
VALUES
('11-12-2019',1,11,1000,12)


--BASIT BIR FATURA_EK TABLOSU OLUSTURALIM.
--ILGILI SQL SORGUSU;
--PERSISTED EKI YAZILMADIGINDA SATIRLARDA VERI TUTLMAZ VE BASKA TABLOLAR ILGILI VERILERE ERISEMEZ.
CREATE TABLE FATURA_EK
(
FATURA_NO INT NOT NULL IDENTITY,
TARIH DATE NOT NULL,
MUSTERI_NO INT NOT NULL,
IRSALIYE_NO INT NOT NULL,
TOPLAM_TUTAR DECIMAL (18,4) NOT NULL,
TOPLAM_KDV DECIMAL (18,4) NOT NULL,
GENEL_TOPLAM AS TOPLAM_TUTAR+TOPLAM_KDV
)

SELECT * FROM FATURA_EK

INSERT INTO FATURA_EK
VALUES
('11-12-2019',1,11,1000,12)