/*
ANSI DISI SYNTAX ILE TABLO BIRLESTIRME VE ILGILI KISTASLARI UYGULAMAK MUMKUNDUR. 
*/

----------------INNER JOIN MANTIGI----------------
--KONTROL WHERE CLAUSE ILE SAGLANIYOR.
--PERSONEL VE PERSONEL MAAS TABLOSUNU ANSI DISI SYNTAX ILE BIRLESTIRELIM.
--ILGILI SQL SORGUSU;
SELECT P.Name,PR.Price 
FROM PERSON P,PRICE PR
WHERE P.ID=PR.PersonId

--PERSONEL VE PERSONEL MAAS TABLOSUNU ANSI DISI SYNTAX ILE MAASI 10.000 TL UZERI OLANLARLA BIRLESTIRELIM.
--ILGILI SQL SORGUSU;
SELECT P.Name,PR.Price 
FROM PERSON P,PRICE PR
WHERE P.ID=PR.PersonId AND PR.Price>10000


----------------LEFT JOIN MANTIGI / ARTIK DESTEKLENMIYOR !!! ----------------
--KONTROL WHERE CLAUSE ICERISINDEKI *= ILE SAGLANIYOR.
--PERSONEL VE PERSONEL MAAS TABLOSUNU ANSI DISI SYNTAX ILE BIRLESTIRELIM.
--ILGILI SQL SORGUSU;
SELECT P.Name,PR.Price 
FROM PERSON P,PRICE PR
WHERE P.ID *= PR.PersonId

--PERSONEL VE PERSONEL MAAS TABLOSUNU ANSI DISI SYNTAX ILE MAASI 10.000 TL UZERI OLANLARLA BIRLESTIRELIM.
--ILGILI SQL SORGUSU;
SELECT P.Name,PR.Price 
FROM PERSON P,PRICE PR
WHERE P.ID *= PR.PersonId AND PR.Price>10000


----------------CROSS JOIN MANTIGI / ARTIK DESTEKLENMIYOR !!! ----------------
--KONTROL FROM SECOMONDEN SONRA SAGLANIYOR.
--PERSONEL VE PERSONEL MAAS TABLOSUNU ANSI DISI SYNTAX ILE BIRLESTIRELIM.
--ILGILI SQL SORGUSU;
SELECT P.Name,PR.Price 
FROM PERSON P,PRICE PR