/*
SQL SERVER ICERISINDE BELIRLI GRUPLAR ICIN HIYERARSIK YAPI OLUSTURABILIRISINIZ.

HIERARCHYID BELIRLEYEREK BU GRUPLAR ARASINDA SINIFLANDIRMA OLUSTURABILIRSINIZ.
*/

--HHIYERARSIK DUZEN ICEREN BIR TABLO OLUSTURALIM.
--ILGILI SQL SORGUSU;
CREATE TABLE URUNHIYERARSISI
(
URUNGRUBU CHAR(3) NOT NULL PRIMARY KEY,
URUNADI VARCHAR(50),
URUNAGACI HIERARCHYID
)

--TABLO ICERISINE VERILER EKLEYELIM.
--ILGILI SQL SORGUSU;
INSERT INTO URUNHIYERARSISI
VALUES
('BLG','BILGISYAR','/')

INSERT INTO URUNHIYERARSISI
VALUES
('DSK','HARDDISK','/1/'),
('RAM','MEMORY','/2/'),
('RD','RD RAM','/2/1/'),
('SD','SD RAM','/2/2/'),
('SCS','SCSI HARDDISK','/1/1/')

--TABLOMUZU KONTROL EDELIM.
SELECT * FROM URUNHIYERARSISI

SELECT *,URUNAGACI.ToString() AS HIYERARSIGRUP FROM URUNHIYERARSISI

--GETANCESTOR() METODU ILE ILGILI KAYIT ATASINI VERIR.
----ILGILI SQL SORGUSU;
SELECT *,
	   URUNAGACI.ToString() AS HIYERARSIGRUP, 
	   URUNAGACI.GetAncestor(1) AS ANAGRUBU 
	   FROM URUNHIYERARSISI

--GETLEVEL() METODU ILGILI KAYITIN SEVIYESINI VERIR.
--ILGILI SQL SORGUSU;
SELECT *,
	   URUNAGACI.ToString() AS HIYERARSIGRUP, 
	   URUNAGACI.GetAncestor(1) AS ANAGRUBU,
	   URUNAGACI.GetAncestor(1).ToString() AS ANAGRUBSTRING,
	   URUNAGACI.GetLevel() AS URUNSEVIYESI
	   FROM URUNHIYERARSISI