/*
MEVCUT YAPILARIMIZDA 'N' ARALIKLI ZAMAN DEGERLERI OLARAK GERIYE VEYA ILERIYE DONUK ISLEMLER GERCEKLESTIREBILIRIZ. 
*/

--'N' AY GERIYE DOGRU GIDEN AYLIK BIR ZAMAN PERIYODU OLUSTURALIM.
--MEVCUT SQL SORGUSU; 
SELECT Tarih,
       CASE WHEN Tarih >= DATEADD(MONTH, -1,  GETDATE())   THEN 'Son 1 Ay' 
			WHEN Tarih >= DATEADD(MONTH, -2,  GETDATE())   THEN 'Son 2 Ay'
	        WHEN Tarih >= DATEADD(MONTH, -3,  GETDATE())   THEN 'Son 3 Ay'
			WHEN Tarih >= DATEADD(MONTH, -4,  GETDATE())   THEN 'Son 4 Ay'
			WHEN Tarih >= DATEADD(MONTH, -5,  GETDATE())   THEN 'Son 5 Ay'
			WHEN Tarih >= DATEADD(MONTH, -6,  GETDATE())   THEN 'Son 6 Ay'
			WHEN Tarih >= DATEADD(MONTH, -7,  GETDATE())   THEN 'Son 7 Ay'
			WHEN Tarih >= DATEADD(MONTH, -8,  GETDATE())   THEN 'Son 8 Ay'
			WHEN Tarih >= DATEADD(MONTH, -9,  GETDATE())   THEN 'Son 9 Ay'
			WHEN Tarih >= DATEADD(MONTH, -10, GETDATE())  THEN 'Son 10 Ay'
			WHEN Tarih >= DATEADD(MONTH, -11, GETDATE())  THEN 'Son 11 Ay'
			WHEN Tarih >= DATEADD(MONTH, -12, GETDATE())  THEN 'Son 12 Ay'
			ELSE 'Diger'
	   END AS Tip
FROM dbo.tTarih
WHERE GETDATE()>= Tarih
ORDER BY Tarih DESC


--'N' AY ILERIYE DOGRU GIDEN AYLIK BIR ZAMAN PERIYODU OLUSTURALIM.
--MEVCUT SQL SORGUSU; 
SELECT Tarih,
       CASE WHEN Tarih >= DATEADD(MONTH, 1,  GETDATE())   THEN 'Gelecek 1 Ay' 
			WHEN Tarih >= DATEADD(MONTH, 2,  GETDATE())   THEN 'Gelecek 2 Ay'
	        WHEN Tarih >= DATEADD(MONTH, 3,  GETDATE())   THEN 'Gelecek 3 Ay'
			WHEN Tarih >= DATEADD(MONTH, 4,  GETDATE())   THEN 'Gelecek 4 Ay'
			WHEN Tarih >= DATEADD(MONTH, 5,  GETDATE())   THEN 'Gelecek 5 Ay'
			WHEN Tarih >= DATEADD(MONTH, 6,  GETDATE())   THEN 'Gelecek 6 Ay'
			WHEN Tarih >= DATEADD(MONTH, 7,  GETDATE())   THEN 'Gelecek 7 Ay'
			WHEN Tarih >= DATEADD(MONTH, 8,  GETDATE())   THEN 'Gelecek 8 Ay'
			WHEN Tarih >= DATEADD(MONTH, 9,  GETDATE())   THEN 'Gelecek 9 Ay'
			WHEN Tarih >= DATEADD(MONTH, 10, GETDATE())   THEN 'Gelecek 10 Ay'
			WHEN Tarih >= DATEADD(MONTH, 11, GETDATE())   THEN 'Gelecek 11 Ay'
			WHEN Tarih >= DATEADD(MONTH, 12, GETDATE())   THEN 'Gelecek 12 Ay'
			ELSE 'Diger'
	   END AS Tip
FROM dbo.tTarih
WHERE GETDATE()>= Tarih
ORDER BY Tarih DESC