/*
PROCEDURE KELIME ITIBARIYLA YAZILIM DUNYASINDAKI MANASI ILE BELIRLI BIR GOREVI YERINE GETIREN PAKETLENMIS BIR DIZI PROGRAM TALIMATLARIDIR.
*/
SELECT * FROM PERSON

--TEMEL PARAMETRESIZ PROCEDURE KALIBI
/*
CREATE PROCEDURE(/PROC ) (PROSEDURE ADI)
AS
BEGIN
		SORGU PARCACIGI
END
*/

--PARAMETRESIZ PROCEDURE
--PERSON TABLOSUNDA VERILERI GETIREN PROCEDURE OLUSTURAN SORGU KALIBI 
CREATE PROCEDURE spGetPerson
AS
BEGIN
	SELECT * FROM PERSON
END

--OLUSTURULAN SORGUYU CALISTIRMAK ICIN
EXECUTE spGetPerson --V1  /IKI KULLANIMIN PERFORMANSI TAMAMEN AYNIDIR
EXEC    spGetPerson --V2
spGetPerson         --V3

--TEMEL PARAMETRELI PROCEDURE KALIBI
/*
CREATE PROCEDURE(/PROC ) (PROSEDURE ADI)
@PARAMETRE1 INT,
@PARAMETREN NVARCHAR(50)  N PARAMETRELI...
AS
BEGIN
		SORGU PARCACIGI
END
*/

--TEK PARAMETRELI PROCEDURE
--DEPARTMANA GORE PERSON TABLOSUNDAKI VERILERI GETIREN PROCEDURE
CREATE PROCEDURE spGetDeparmentPerson
@Department int
AS
BEGIN
	SELECT * FROM PERSON
	WHERE DepartmentID = @Department
END

--PROCEDURE CALISTIRILIRSA
EXECUTE spGetDeparmentPearson 1           --V1  
EXEC    spGetDeparmentPearson 1           --V2
spGetDeparmentPearson 1                   --V3
spGetDeparmentAndCityPerson @Department=1 --V4

--COK PARAMETRELI PROCEDURE
--DEPARTMANA VE SEHIRE GORE PERSON TABLOSUNDAKI VERILERI GETIREN PROCEDURE
CREATE PROCEDURE spGetDeparmentAndCityPerson
@Department int,
@City nvarchar(50)
AS
BEGIN
	SELECT * FROM PERSON
	WHERE DepartmentID = @Department AND City = @City
END

--PROCEDURE CALISTIRILIRSA
EXECUTE spGetDeparmentAndCityPerson 1,'ISTANBUL'            --V1  
EXEC    spGetDeparmentAndCityPerson 1,'ISTANBUL'            --V2
spGetDeparmentAndCityPerson 1,'ISTANBUL'                    --V3
spGetDeparmentAndCityPerson @Department=1,@City='ISTANBUL'  --V4

--PROCEDURE OBEGINI KONTROL ETMEK ICIN sp_helptext(PROCEDURE ADI)
sp_helptext spGetDeparmentAndCityPerson

--MEVCUT PROCEDURE UZERINDE DEGISIM GERCEKLESTIRINCE UZERINE YAZMAK ICIN CREATE~ALTER KOMUTU DONUSUMU GERCEKLESIR
ALTER PROCEDURE spGetDeparmentAndCityPerson
@Department int,
@City nvarchar(50)
AS
BEGIN
	SELECT * FROM PERSON
	WHERE DepartmentID = @Department AND City = @City
	ORDER BY Name ASC
END

--PROCEDURE SILMEK ICIN
DROP PROCEDURE spGetDeparmentAndCityPerson

--PROCEDURE KILITLEMEK ICIN WITH ENCRYPTION KOMUTU KULLANILIR
ALTER PROCEDURE spGetDeparmentAndCityPerson
@Department int,
@City nvarchar(50)
WITH ENCRYPTION
AS
BEGIN
	SELECT * FROM PERSON
	WHERE DepartmentID = @Department AND City = @City
	ORDER BY Name ASC
END

--BELLI BIR YASTA BULUNAN PERSONEL SAYISINI VEREN PROCEDURE
CREATE PROCEDURE spGetCountAgePerson
@Age int,
@PersonCount int OUTPUT
AS
BEGIN
	 SELECT @PersonCount=COUNT(*) FROM PERSON
	 WHERE Age=@Age
END

--PROCEDURE CALISTIRILIRSA
DECLARE @TotalCount int
EXECUTE    spGetCountAgePerson 23, @TotalCount 
OUTPUT PRINT @TotalCount  	--V1  

DECLARE @TotalCount int
EXEC    spGetCountAgePerson 23, @TotalCount 
OUTPUT PRINT @TotalCount    --V2

--sp_help (PROCEDURE ADI) PROCEDURE OLUSTURMA TARIHI,TIPI,ISMI,OLUSTURAN,PARAMETRELER... HAKKINDA BILGI VERIR
--TABLO,FONKSIYON VS... OBJELER HAKKINDA BILGI VERIR
sp_help spGetCountAgePerson

--PROCEDURE SORGUSUNU GERI DONDURUR
sp_helptext spGetCountAgePerson

--ADI,GUNCELLEMESI VS... GENEL BILGILERI GERI DONDURUR
sp_depends spGetCountAgePerson

--PROCEDURELER OUTPUT PARAMETER BIR CIKIS DEGERI VEREN PARAMETRELER OLUSTURABILIR
--TOPLAM PERSONEL SAYISINI VEREN PROCEDURE
CREATE PROCEDURE spGetTotalCount
AS
BEGIN
	RETURN (SELECT COUNT(ID) FROM PERSON)
END

DECLARE @Total int
EXECUTE @Total = spGetTotalCount  
PRINT @Total


--ID YE GORE ADI VEREN PROCEDURE
CREATE PROCEDURE spGetNameById
@Id int,
@Name nvarchar(50) OUTPUT
AS
BEGIN
	SELECT @Name = Name FROM PERSON 
	WHERE ID = @Id
END

DECLARE @Name nvarchar(50)
EXECUTE spGetNameById 1, @Name OUTPUT
PRINT 'ADI = ' +@Name
