/*
	SQL SERVER UZERINDE HERHANGI BIR VERI DEGISTIRME ISLEMINDE DEGISIKLIK ANINDA  VERITABANINA YANSIMAZ. 
	UZERINDE DEGISIKLIK YAPILAN SAYFALAR DAHA ONCE DISKTEN  HAFIZAYA ALINMAMIS ISE ONCELIKLE TAMPON HAFIZA (BUFFER CACHE) DENILEN  HAFIZA BOLGESINE CAGRILIR. 
	HAFIZA BOLGESINDEKI SAYFALAR UZERINDE DEGISIKLIKLER  GERCEKLESTIRILIR VE VERITABANINA HEMEN YANSITILMAZ.
	HAFIZAYA CAGRILARAK UZERINDE  DEGISIKLIK YAPILAN SAYFALARA KIRLI SAYFA (DIRTY PAGE) DENIR.
	KIRLI SAYFALARDA TUTULAN  DEGISIKLIKLER GEREKLI IS SURECLERI TAMAMLANDIKTAN SONRA VERITABANINA KAYDEDILIR.
	KIRLI SAYFALARIN VERITABANINA KAYDEDILME ISLEMINE ISE ARINDIRMA (FLUSHING) DENIR.
*/

ROLLBACK TRANSACTION --KILINTLENMIS ISLEME DAYALI ILGILI SAYFADA (KILITLENEN) CALISTIRILMASI GEREKMEKTEDIR.


--XACT_STATE() KULLANIMI
ALTER PROC sp_XRoot(
 XXX
)
AS
BEGIN TRY
 BEGIN TRANSACTION
		......
SQL SERVER TRANSACTION 469
		......
	COMMIT
 END TRY
BEGIN CATCH
IF(XACT_STATE()) = -1 --TRANSACTION FAALIYETININ DEVAM ETTIGINI YA DA TAMAMLANDIGINI KONTROL ETMEKTE. {XACT_STATE() FONKSIYONU}
BEGIN
 PRINT @@ERROR + 'HATA'
ROLLBACK TRAN
END
IF(XACT_STATE()) = 1
BEGIN
 PRINT @ERROR + 'HATA VAR, FAKAT ISLEM GERCEKLESTI.'
COMMIT TRAN
END
END CATCH;



SELECT * FROM AdventureWorks2019.Person.Person (READCOMMITTED);    --BASKA TRANSACTION TARAFINDAN GUNCELLENMEKTE OLAN TABLO VERILERINI OKUYAMAZ.READ_COMMITTED_SNAPSHOT OZELLGI AKTIF ISE KULLANILAMAZ.

SELECT * FROM AdventureWorks2019.Person.Person (READUNCOMMITTED);  --BASKA TRANSACTION TARAFINDAN GUNCELLENEN FAKAT ISLEMLERI TAMAMLANMAMIS TABLO VERILERINI OKUYABILIR.
SELECT * FROM AdventureWorks2019.Person.Person (NOLOCK);           --READUNCOMMITTED ILE AYNI GOREVI USTLENIR.

SELECT * FROM AdventureWorks2019.Person.Person (READCOMMITTEDLOCK);--BASKA TRANSACTION TARAFINDAN GUNCELLENEN FAKAT ISLEMLERI TAMAMLANMAMIS TABLO VERILERINI OKUYABILIR.FAKAT OPSIYONELDIR.

SELECT * FROM AdventureWorks2019.Person.Person (HOLDLOCK);         --KILITLEME ISLEMINI TABLO BITIMINE KADAR SURMESINI VE TRANSACTION BAZINDA KILITLME YAPILAMASINI SAGLAR.
SELECT * FROM AdventureWorks2019.Person.Person (SERIALIZABLE);     --HOLDLOCK ILE AYNI GOREVI USTLENIR.

SELECT * FROM AdventureWorks2019.Person.Person (REPEATABLEREAD);   --GUNCELLENEN FAKAT HENUZ COMMIT EDILMEMIS VERILER COMMIT EDILENE KADAR OKUNAMAZ VEYA BASKA TRANSACTIONLAR TARAFINDAN GUNCELLENEMEZ.

SELECT * FROM AdventureWorks2019.Person.Person (READPAST);		   --TRANSACTION SURECINDE KILIT BULUNMAYAN KAYITLAR ELDE EDILIR.

SELECT * FROM AdventureWorks2019.Person.Person (PAGLOCK);		   --SAYFA SEVIYESINDE KULLANILAN KILITLERDIR.

SELECT * FROM AdventureWorks2019.Person.Person (TABLOCK);		   --TABLO SEVIYESINDE KULLANILAN KILITLERDIR.

SELECT * FROM AdventureWorks2019.Person.Person (UPDLOCK);		   --TRANSACTION SONLANANA KADAR VERI GUNCELLEMESINE IZIN VERMEYEN KILIT MODELI.



sp_who --KIM NELER YAPIYOR ?

sp_lock --KILITLI OLAN KAYNAKLARI GORUNTULEMEK ICIN KULLANILIR.

		--ACTIVITY MONITOR

BEGIN TRAN
UPDATE AdventureWorks2019.Person.PersonPhone
SET PhoneNumberTypeID = PhoneNumberTypeID - 50000000000000000000000000000
WHERE PhoneNumberTypeID = '000000000000000000000000000000000000065127';

SELECT * FROM AdventureWorks2019.Person.PersonPhone;