/*
BELIRLI ZAMANLARDA ELDE ETMIS OLDUGUNUZ VERILERI BELIRLI KALIPLARA GORE DUZENLEMENIZ GEREKEBILIR.
OZELLIKLE VERI ICERISINDEN KARAKTER SILIMI YA DA EKLENMESI GIBI EYLEMLER.

STUFF() FONKSIYONU ILE DIZE ICERISINDEKI BELIRLI BIR KARAKTER DEGEREINI/GRUBUNU SILER VE SONRASINDA BELIRTILEN KARAKTER GURBUNU BELIRTILEN SIRA DAHILINDE EKLER.

*/

--MEVCUT VERI UZERINDE DUZNELEME ISLEMI YAPILMAK ISTENDIGINDE;
SELECT 
      'AZ-1114524' AS Fatura,
	  STUFF('AZ-1114524', 3, 1, '-Kampanya-') FaturaKampanya;


--MEVCUT VERILERI GRUP/KUME HALINDE GOSTERMEK ISTENDIGIMIZDE;
SELECT il.IlId, il.IlAdi AS Sehir,
	STUFF
	(
	  (
		SELECT 
		', ' + IlceAdi 
		FROM Ilceler AS ilce 
		WHERE il.IlId = ilce.IlId
		FOR XML PATH('')
	  ), 1, 1, ''
	) AS Ilceler
FROM Iller AS il
/*ILID:2   IL:ADIYAMAN	 ILCELERI:ADIYAMAN, BESNİ, ÇELİKHAN, GERGER, GÖLBAŞI, KAHTA, SAMSAT, SİNCİK, TUT, MERKEZ*/