/*
BAZI TABLOLAR ICERISINDE YER ALAN DEGERLER KUMELENMEK YA DA YENIDEN IFADELENDIRILMEK ISTENEBILIR. (AYRISTIRMA/SECME VB.)
BUNLARI SORGU ILE YADA HARDCORE YONTEMLERLE DEGISTIRMEDEN FARKLI BIR FONKSIYON ILE ISTEDIGINIZ ANLAMLI MODEL HALINE DONUSTUREBILIRIZ.
*/

SELECT * FROM PERSON
SELECT * FROM DEPARTMENT

--CASE(X ISE Y; Z ISE V VB. DEGER BELIRLEMELERI ILE KUMELEMEDE BULUNABILMEMIZ SAGLAMAKTADIR.)
--YENI BIR ANA DEPARTMAN MODELI OLUSTURALIM;
SELECT 
      CASE 
	       WHEN D.Department='YAZILIM' OR D.Department='IT'       THEN 'BILGI TEKNOLOJILERI'
		   WHEN D.Department='FINANS'  OR D.Department='MUHASEBE' THEN 'MALI BIRIMLER'
		   ELSE 'DIGER BIRIMLER'
	  END AS DepartmanGrupları
FROM PERSON P
LEFT JOIN DEPARTMENT D ON D.DepartmentID=P.DepartmentID 


--YA DA TEKBIR PARAMETRE ISE ALAN ADINI YINELEMELI KULLANMADAN DA GRUPLAMADA BULUNABILIRSINIZ.
SELECT 
      CASE 
	       D.Department
	       WHEN 'YAZILIM' OR 'IT'       THEN 'BILGI TEKNOLOJILERI'
		   WHEN 'FINANS'  OR 'MUHASEBE' THEN 'MALI BIRIMLER'
		   ELSE 'DIGER BIRIMLER'
	  END AS DepartmanGrupları
FROM PERSON P
LEFT JOIN DEPARTMENT D ON D.DepartmentID=P.DepartmentID 


--FARKLI DURUMLARDA ISE EK PARAMETRELER ILE GRUPLAMALARA YAN KOSULLAR DA EKLEYEBILIRSINIZ.
SELECT 
      CASE 
	       WHEN (D.Department='YAZILIM'  OR D.Department='IT')       AND P.ID> 1000 THEN 'BILGI TEKNOLOJILERI'
		   WHEN (D.Department='FINANS'   OR D.Department='MUHASEBE') AND D.ID<>1    THEN 'MALI BIRIMLER'
		   ELSE 'DIGER BIRIMLER'
	  END AS DepartmanGrupları
FROM PERSON P
LEFT JOIN DEPARTMENT D ON D.DepartmentID=P.DepartmentID 