/*
BAZI DURUMLARDA VERI ANALIZI ADINA KELIME KABILINA YONELIK ARAMA YAPMAMIZ GEREKEBILIR.

ASAGIDAKI OPERATORLER SURECTE JOKER KARAKTERLERIMIZ OLACAKTIR;
% : 0 YA DA DAHA FAZLA KARAKTER ICIN,
_ : TEK BIR KARAKTER ICIN,
[ ] : BELIRTILEN KARAKTERLERDEN HERHANGI BIRI,
[ - ] : ILGILI BELIRTILEN ARALIKTAKI KARAKTERLERDEN HERHANGI BIRI.

ASAGIDA; DENETIM BIRIMININ GERCEKLESEN CIRODA YER ALAN FATURALARA YONELIK BIR KONTROLUNUN GERCEKLESTIRILMESI ORNEGI MEVCUT.

KONTROL:

1. ILK KARAKTER A-F VE ARALARINDAKI HERHANGI BIR KARAKTER OLABILIR.
2. IKINCI KARAKTER X YA DA 0 OLABILIR.
3. UCUNCU KARAKTER "-" / "TIRE" OLMALIDIR.
4. DORDUNCU KARAKTER TEK OLMALIDIR.
5. BESINCI KARAKTER 5 OLMALIDIR.
6. ALTINCI KARAKTER 2 OLMALIDIR.
6. KALAN KISIM ISE HERHANGI BIR KARAKTER OLABILIR.

*/

SELECT 
      * 
FROM [MBT].[dbo].[CariCiroMBT] WITH (NOLOCK)
WHERE FaturaSeriSira LIKE '[A-F][X0]-_52%'