/*
VERILERIMIZI MODELLERKEN BAZEN TUR DONUSUMLERINE IHTIYAC DUYARIZ.
AMAC BIRBIRINE DONUSTURULEBILIR VERILERI DONUSTURMEK VE GEREKSINIM DOGRULTUSUNDA UYGUN BIR SEKLILDE VERIYI KULLANMAK.
SQL SERVER ICERISINDE BULUNAN CAST(),TRY_CAST() VE CONVERT() FONKSIYONLARI TAMAMEN ISLEVSEL OLARAK GEREKSINIMLERIMIZI BU YONDE KARSILAR.
*/

USE BussinesLife
SELECT * FROM PERSON

--DATETIME OLARAK DEPOLADIGIMIZ DOGUM TARIHINI CAST EDEREK STRING VERSIYONA DONUSTURUYORUZ
--DONUSUM SONRASINDA DATETIME OLARAK OLUSTURDUGUMUZ VERI /Jun 18 1992 12:00AM/ YAPISINA DONUSUYOR
SELECT Name,EMail,City, CAST(BirthDate AS nvarchar) AS [Dogum Gunu] FROM PERSON 
SELECT Name,EMail,City, CAST(LEFT(BirthDate,12) AS nvarchar) AS [Dogum Gunu] FROM PERSON 


/*
	CONVERT STILLERI

	
		101					mm/dd/yyyy

		102					yy.mm.dd

		103					dd/mm/yyyy

		104					dd.mm.yy

		105					dd-mm-yy

		106(1)				dd mon yy

		107(1)				Mon dd, yy

		108					hh:mi:ss

		9 or 109 (1,2)		mon dd yyyy hh:mi:ss:mmmAM (or PM)

		110					mm-dd-yy

		111					yy/mm/dd

		112					yymmdd		yyyymmdd

		13 or 113 (1,2)		dd mon yyyy hh:mi:ss:mmm(24h)

		114					hh:mi:ss:mmm(24h)

		20 or 120 (2)		yyyy-mm-dd hh:mi:ss(24h)

		21 or 121 (2)		yyyy-mm-dd hh:mi:ss.mmm(24h)

		126 (4)				yyyy-mm-ddThh:mi:ss.mmm 

		127(6, 7)			yyyy-mm-ddThh:mi:ss.mmmZ	

		130 (1,2)			dd mon yyyy hh:mi:ss:mmmAM

		131 (2)				dd/mm/yy hh:mi:ss:mmmAM

	KULLANIM; CONVERT(NVARCHAR,BirthDate,101)  ...VB

*/

--CONVERT() FONKSIYONU ILE DOGUM GUNU DUZENLEMESI
SELECT ID,Name,City,CONVERT(NVARCHAR,BirthDate,107) AS [Dogum Gunu] FROM PERSON

--AYLARA GORE DOGUM GUNU SAYISI DAGILMINI VEREN SORGU
SELECT SUM(1) AS [Toplam Sayi],CAST(MONTH(BirthDate) AS nvarchar) AS [Ay No] FROM PERSON
GROUP BY  MONTH(BirthDate)

--V2
SELECT SUM(1) AS [Toplam Sayi],MONTH(BirthDate) FROM PERSON
GROUP BY MONTH(BirthDate)

SELECT TRY_CAST('2345' AS DECIMAL(10, 2)) AS [Deger]
 
SELECT TRY_CAST(123.456 AS VARCHAR(50)) AS Result; 
 

--TRY_CAST() FONKSÝYONU CAST() FONKSIYONU GIBI CALISIP HATA ATMAK YERINE DONUSUMU GERCEKLESEMEYEN DEGERLER ICIN 'NULL' DEGERI DONDURUR
SELECT TRY_CAST ('19/14/2017' AS DATETIME2 ) AS [Sonuc]
SELECT TRY_CAST ('INT GÝBÝ' AS int) AS [Sonuc]
SELECT TRY_CAST (NULL AS INT) AS [Sonuc]

--ILGINC BIR DONUSUM DENERSEK BU KEZ 'NULL' YERINE DOSGRUDAN SISTEM HATASI ALIRIZ
SELECT TRY_CAST (65 AS XML) [Sonuc] 
SELECT TRY_CAST (65 AS hierarchyid) [Sonuc] 