/*
######################################################### 18456 HATASI #########################################################

MICROSOFT SQL SERVERDA KIMLIK DOGRULAMASI YAPMAYA CALISTIGINIZDA ORTAYA CIKAN 18456 HATASININ TIPIK NEDENLERINE GOZ ATACAGIZ.
NASIL DUZELTECEGIMIZI INCELEYECEGIZ.     

MICROSOFT SQL SERVER HATA 18456, YEREL YONETICI ALTINDA, ETKI ALANI YONETICISI ALTINDA VE SA KULLANICISI ALTINDA GIRIS YAPMAYA CALISTIGINIZDA ORTAYA CIKABILIR.

GIRIS BASARISIZLIGININ EN YAYGIN NEDENLERI OLDUKCA FARKLI DURUMLAR OLABILIR;  
*YANLIS KULLANICI ADI VEYA SIFRE;  
*ENGELLI SQL KIMLIK DOGRULAMA BILGILERI;  
*SURESI DOLMUS SIFRE;
*SILINMIS KULLANICI HESABI.

ORNEGIN; MICROSOFT SQL SERVER MANAGEMENT STUDIO YU CALISTIRIP "SA" HESABININ ALTINDAKI SQL SUNUCUSUNDA OTURUM ACMAYI DENERSENIZ,   
ASAGIDAKI HATA GORUNUR;    

TITLE: CONNECT TO SERVER  
CANNOT CONNECT TO SERVER\SQL.
ADDITIONAL INFORMATION:  LOGIN FAILED FOR USER SA. (MICROSOFT SQL SERVER, ERROR: 18456)

BASARISIZ KIMLIK DOGRULAMASININ KESIN NEDENLERI,HATA DURUMU YARDIMIYLA BELIRLENEBILIR.   

MICROSOFT SQL SERVER HATASI 18456 NEDENI HAKKINDA DAHA AYRINTILI BILGI ALMAK ICIN, SQL SERVER HATA GUNLUGU DOSYASINI   
-ERROR.LOG ACMANIZ GEREKIR.     

BU, MSSQL\LOG KLASORU ALTINDA BULUNAN DUZ METIN DOSYASIDIR.   

ORNEGIN, ERROR.LOG DOSYASINDA ASAGIDAKI SATIRLARI GOREBILIRSINIZ:    

2019-10-29 13:48:11.32 LOGON       
ERROR: 18456, SEVERITY: 14, STATE: 8.  
2019-10-29 13:48:11.32 LOGON       
LOGIN FAILED FOR USER SA. REASON: PASSWORD DID NOT MATCH THAT FOR THE LOGIN PROVIDED. [CLIENT: 10.27.65.29]    

GORDUGUNUZ GIBI, KULLANICI YANLIS BIR SIFRE ILE GIRIS YAPMAYA CALISMIS.  

ASAGIDAKI TABLODA 18456 NUMARALI HATA ICIN OLASI DURUMLAR VE HER BIRI ICIN KISA ACIKLAMA BULUNMAKTADIR;    

DURUM HATA ACIKLAMASI  
1-HATA BILGISI MEVCUT DEGIL. BU DURUM GENELLIKLE HATA AYRINTILARINI ALMA IZNINIZIN OLMADIGI ANLAMINA GELIR.
2-GECERSIZ KULLANICI KIMLIGI  
5-GECERSIZ KULLANICI KIMLIGI  
6-SQL KIMLIK DOGRULAMA ILE BIR WINDOWS GIRIS ADI KULLANMAYA CALISIN. 
7-GIRIS DEVRE DISI BIRAKILDI  
8-SIFRE YANLIS  
9-SIFRE GECERLI DEGIL  
11-12 GECERLI GIRIS ANCAK SUNUCU ERISIM HATASI.  
13-SQL SERVER HIZMETI DURAKLATILDI.
16-YETKILENDIRME DOGRU, ANCAK SECILEN VERITABANINA ERISIME IZIN VERILMIYOR.  
18-PAROLA DEGISTIR ISLEMI GEREKLI.
27-ILK VERITABANI BULUNAMADI.
38-KULLANICI TARAFINDAN ISTENEN VERITABANI BULUNAMADI COGU DURUMDA,KULLANICILAR, SQL SERVER KIMLIK DOGRULAMASINI KULLANARAK 
KIMLIK DOGRULAMASI YAPMAYA CALISTIKLARINDA DURUM 6 DA MICROSOFT SQL SERVER HATASI 18456 ILE KARSILASIRLAR.

SQL BAGLANTI PENCERELERINDE, KIMLIK DOGRULAMA TURU OLARAK WINDOWS KIMLIK DOGRULAMASINA GECIN VE 
YEREL YONETICI HAKLARINA SAHIP BIR HESAP ALTINDA SQL VERITABANINA BAGLANMAYI DENEYIN.    

WINDOWS KIMLIK DOGRULAMA DUZGUN CALISIYORSA,SQL ORNEGINIZIN OZELLIKLERINI ACMANIZ VE GUVENLIK SEKMESINE GITMENIZ GEREKIR.

SUNUCU KIMLIK DOGRULAMA MODUNU SQL SERVER VE WINDOWS KIMLIK DOGRULAMA MODUNA DEGISTIRIN (BU KARMA KIMLIK DOGRULAMA MODU).

DEGISIKLIKLERI UYGULAMAK ICIN, SAG TIKLAYIP ICERIK MENUSUNDEN YENIDEN BASLAT SECENEGINI SECEREK SQL SERVER HIZMETLERINI YENIDEN BASLATMANIZ GEREKIR.

SQL SERVER KIMLIK DOGRULAMA MODUNDA SQL HESABININ (SA VEYA OZEL KULLANICI) ALTINDAKI SUNUCUYA GIRIS YAPMAYI DENEYIN.

SA HESABI DEVRE DISI BIRAKILMISSA VEYA SIFREYI BILMIYORSANIZ, SIFREYI ETKINLESTIRIP SIFIRLAMAK ICIN MANAGEMENT STUDIO KONSOLUNDA ASAGIDAKI SORGULARI CALISTIRIN.

ALTER LOGIN SA ENABLE;  
GO  
ALTER LOGIN SA WITH PASSWORD = <SOME_SUPER_STRONG_PASSWORD>;  
GO
*/